### DISCUSSION TITLE
Does SigNoz support metrics as well?

### DISCUSSION THREAD

**Discussion by MacNale** [SigNoz/signoz#172] [General]
Team,

SaaS vendors like Datadog supports collecting traces. These traces are processed to produce some metrics like latency/error rate/throughput etc. Analytics can be performed on the top of these metrics.

These vendors also collect a lot of infrastructure metrics like memory usage. Does SigNoz also support such metrics?

**Comment by pranay01** [comment]
Hi @MacNale  Thanks for your question.

We do support traces currently and application metrics like latency, error rates, throughput etc.

 We don't support infrastructure metrics currently (memory usage, etc) - but support for introducing custom metrics is in our roadmap. Once that is done, you should be able to send infrastructure metrics.

Do you have any specific use case around infra metrics? Would love to hear that

**Reply by MacNale** [reply]
DevOps Team look at the traces (RED OR USE method). The system programmers look at infrastructure metrics. In fact, they wish to see together.  If p99 latency degrades, then they would like to see what is going on the system.

**Reply by pranay01** [reply]
Agree. We plan to ship custom metrics soon - i.e. you will be able to send any metrics to SigNoz from various exporters. The infra metrics use case would be supported then.

**Comment by kinthaiofficial** [comment]
Yes, SigNoz supports metrics — it uses the OpenTelemetry data model so you get traces, metrics, and logs all in one place with correlation.

For metrics specifically you can use:
1. **OTLP push** from your SDK (most common)
2. **Prometheus scrape** via the collector's `prometheusreceiver`

```yaml
# collector config to scrape Prometheus endpoints
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'myapp'
          static_configs:
            - targets: ['localhost:8080']

exporters:
  otlp:
    endpoint: "your-signoz-otel-collector:4317"
```

One thing worth noting: the metrics + trace correlation in SigNoz is genuinely useful. When a metric spikes, you can click through to the traces from that time window. We use this pattern for monitoring agent performance — tracking per-agent request latency, tool call counts, and error rates, then drilling into specific traces when something looks off.

The attribute-based filtering (filtering metrics by `agent_id` label) works the same way as trace attributes, which makes the unified model nice once you're used to it.
