### DISCUSSION TITLE
"Service Name" and Hostname not showing up for logs

### DISCUSSION THREAD

**Discussion by davispuh** [SigNoz/signoz#6328] [General]
Hi!

I just setup SigNoz with Journald Receiver to ingest system logs and they all show up fine in logs.
but these are always empty
![image](https://github.com/user-attachments/assets/7f89dfda-b89c-48d0-99d0-204265df3f1a)

log entries include all necessary metadata like `service.name` and `host.name`
![image](https://github.com/user-attachments/assets/4561cc2f-1965-4645-8a9c-20e9cd1ff227)

**Comment by davispuh** [comment]
Oh, I had `service.name` as Attribute (in UI shows as `Tag`). Now I moved it to Resource and Service Name works now.

![image](https://github.com/user-attachments/assets/191340be-0a51-4a51-ab61-3656cb62623f)

But Hostnames are still empty

**Reply by KieranP** [reply]
@davispuh To get host name, host id, etc type metrics, you need to use the `resourcedetection` processor, and then add it to the service pipeline. That will add all sorts of `host.*` and `cloud.*` metrics available. Here is what I am using:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
        metrics:
          system.cpu.logical.count:
            enabled: true
      disk: {}
      load:
        cpu_average: true
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.limit:
            enabled: true
      network: {}
      paging: {}
      process:
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
      processes: {}
  prometheus:
    config:
      global:
        scrape_interval: 30s
      scrape_configs:
        - job_name: otel-collector-binary
          static_configs:
            - targets: ["localhost:8888"]
  filelog:
    include:
      - /var/log/nginx/access.log
      - /var/log/nginx/error.log
      - /var/log/commands.log
      - /var/log/auth.log

processors:
  resource:
    attributes:
      - key: deployment.environment
        value: production
        action: upsert
      - key: service.name
        value: demo
        action: upsert
  resourcedetection:
    detectors: [env, system, ec2]
    timeout: 2s
    system:
      hostname_sources: [os]
  batch:
    send_batch_size: 1000
    timeout: 5s

extensions:
  health_check: {}
  zpages: {}

exporters:
  otlp:
    endpoint: "10.0.0.10:4317"
    tls:
      insecure: true

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: "localhost"
                port: 8888
  extensions: [health_check, zpages]
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics, prometheus]
      processors: [resource, resourcedetection, batch]
      exporters: [otlp]
    traces:
      receivers: [otlp]
      processors: [resource, resourcedetection, batch]
      exporters: [otlp]
    logs:
      receivers: [otlp, filelog]
      processors: [resource, resourcedetection, batch]
      exporters: [otlp]
```
