### DISCUSSION TITLE
Configure multiple RabbitMQ brokers

### DISCUSSION THREAD

**Discussion by blancqua** [SigNoz/signoz#7600] [Q&A] [answered]
We are having multiple rabbitmq brokers (one for test, acceptance, prod etc.). We'd like to export metrics to Signoz. In a single collector, I seem to only be able to [configure 1 broker](https://signoz.io/blog/opentelemetry-rabbitmq-metrics-monitoring/#step-3---setting-up-the-configuration-file). I could set up multiple otel-collectors, but the [dashboard](https://github.com/SigNoz/dashboards/blob/main/rabbitmq/rabbitmq.json) seems to assume there is only one broker. There is on easy way to filter per environment or at least I am not finding it. I could use `rabbitmq.node.name` but ideally I somehow add the environment name in the metrics.

TL;DR:
- Can I configure multiple rabbitmq connections in 1 Otel Collector?
- Can I easily filter the default rabbitmq dashboard per environment, if not, how are you doing this?

Apologies if this is somehow a newbie question, quite new to Signoz and OpenTelemetry.

**Comment by blancqua** [comment]
The first question I figured out [here](https://opentelemetry.io/docs/collector/configuration/#basics) :-); 

I can name each RabbitMQ receiver by appending `/<name>`

**Comment by blancqua** [comment, marked as answer]
And the second question I also managed, by adding a specific attributes processor per rabbitmq connection, and creating a different pipeline.

I'm altering the basic dashboard now to be able to filter on environment/vhost.

```
receivers:
  ...
  rabbitmq/testing:
    endpoint: ...
  rabbitmq/staging:
    endpoint: ...
processors:
  attributes/testing:
    actions:
      - key: deployment.environment
        value: testing
        action: insert
  attributes/staging:
    actions:
      - key: deployment.environment
        value: staging
        action: insert
...
service:
  ...
  pipelines:
    metrics/rabbit-testing:
      receivers: [rabbitmq/testing]
      processors: [batch, attributes/testing]
      exporters: ...
    metrics/rabbit-staging:
      receivers: [rabbitmq/staging]
      processors: [batch, attributes/staging]
      exporters: ...
...
```
