### DISCUSSION TITLE
signoz k8s-infra k8sEvents logs missing

### DISCUSSION THREAD

**Discussion by cndowel** [SigNoz/signoz#7663] [Q&A]
Hello,

Would just like to preface this with i am new to otel use so forgive me if i am missing something basic. I am installing a self hosted Signoz and k8s-infra helm chart for kubernetes cluster monitoring. By default the k8s-infra helm chart shows that k8sevents are enabled to be collected. I can see in the otelDeployment pod logs that the receiver is being created, but nothing else related to k8sevents in general. 

`{"level":"info","ts":1744896335.740436,"caller":"k8seventsreceiver@v0.109.0/receiver.go:67","msg":"starting to watch namespaces for the events.","kind":"receiver","name":"k8s_events","data_type":"logs"}`

I set up the preconfigured dashboard from Signoz to show k8sevents related information, and am assuming that events are being found (based on the event count on the dashboard, screenshot below) but no other event information is shown.

![Screenshot at 2025-04-17 09-43-11](https://github.com/user-attachments/assets/6ea210fb-d0ec-42f8-85d3-b393d5536ca0)

Is there some sort of additional configuration that is needed in order for these events to be consumed/read? Below are all the values used in my charts. I am installing the latest versions of both charts:

Signoz additional values:
```
USER-SUPPLIED VALUES:
clickhouse:
  initContainers:
    udf:
      enabled: false
  installCustomStorageClass: true
```

k8s-infra additional values:
```
USER-SUPPLIED VALUES:
otelAgent:
  config:
    exporters:
      logging:
        loglevel: debug
  extraVolumeMounts:
  - mountPath: /var/lib/test
    name: test
  extraVolumes:
  - hostPath:
      path: /var/lib/test
      type: Directory
    name: test
otelCollectorEndpoint: http://signoz-otel-collector.monitoring.svc.cluster.local:4317
otelInsecure: true
presets:
  loggingExporter:
    enabled: false
  logsCollection:
    include:
    - /var/lib/test/pods/*/*/*.log
  otlpExporter:
    enabled: true
```

Also any insight on how to get better debug logs for the otelDeployment pod would be greatly appreciated
