### ISSUE TITLE
Unable to export metrics using Otel collector from Otel Operator

### ISSUE THREAD

**Issue by thunko** [SigNoz/signoz#1011]
## Bug description

hi !
I'm trying to export k8s infra metrics to Signoz as indicated here:
https://signoz.io/docs/tutorial/kubernetes-infra-metrics/#steps-to-export-k8s-metrics-to-signoz

In my case I'm running Signoz in the same cluster where applications are, therefore updated the endpoint accordingly but I can't plot any metrics as indicated in your docs.
One note is that I have installed the collector through Otel operator, and I had it up and running. So I expected updating the endpoint should be enough ?

So to make it clear I have the following:
```
➜  ~ k -n platform get pod
NAME                                                        READY   STATUS    RESTARTS   AGE
chi-signoz-cluster-0-0-0                                    1/1     Running   0          20h
clickhouse-operator-8cff468-jnhwn                           2/2     Running   0          20h
my-release-signoz-alertmanager-0                            1/1     Running   0          20h
my-release-signoz-frontend-679745cc99-4xrwj                 1/1     Running   0          20h
my-release-signoz-otel-collector-54d458dd8b-z24bp           1/1     Running   0          20h
my-release-signoz-otel-collector-metrics-5dc97557f6-fngtt   1/1     Running   0          20h
my-release-signoz-query-service-0                           1/1     Running   0          20h
my-release-zookeeper-0                                      1/1     Running   0          20h

➜  ~ k -n testns-0 get pod
NAME                        READY   STATUS    RESTARTS   AGE
daemonset-collector-s8d45   1/1     Running   0          24m
daemonset-collector-wl7d8   1/1     Running   0          24m
daemonset-collector-wwk9z   1/1     Running   0          24m
```

My otel collector config:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: daemonset
  namespace: testns-0
spec:
  mode: daemonset
  hostNetwork: true
  securityContext:
    privileged: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

      # Data sources: metrics
      prometheus:
        config:
          scrape_configs:
            - job_name: "otel-collector"
              scrape_interval: 5s
              static_configs:
                - targets: ["localhost:8888"]

      # Data sources: metrics
      hostmetrics:
        scrapers:
          cpu:
          disk:
          filesystem:
          load:
          memory:
          network:

    exporters:
      prometheus:
        endpoint: "latest-prometheus-server.default.svc.cluster.local:80"
        namespace: "default"

      otlp:
        endpoint: "my-release-signoz-otel-collector.platform.svc.cluster.local:4317"
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp,hostmetrics,prometheus]
          processors: []
          exporters: [prometheus,otlp]
```

this way trying to get the receiver/exporter configured in testns-0  to export metrics to Signoz backend

![image](https://user-images.githubusercontent.com/25479180/164695338-171ab8eb-3836-4a46-8dfe-4df0bdc6468f.png)

what could I be missing ?
Thank you

## Expected behavior

be able to plot one of the [metris](https://signoz.io/docs/tutorial/kubernetes-infra-metrics/#list-of-metrics-from-kubernetes-receiver) on Signoz

## How to reproduce

1. Install Otel collector through [Otel Operator helm chart](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator)
2. Install [Signoz instance](https://signoz.io/docs/install/kubernetes/)
3. Try [plotting a query](https://signoz.io/docs/userguide/dashboards/#add-a-graph-to-a-dashboard)

## Version information 
* **Signoz version**: 0.7.5
* **Browser version**:
* **Your OS and version**: k8s run on Fedora CoreOS 35.20220327.3.0
* **Your CPU Architecture**(ARM/Intel): x86_64 / Intel

**Comment by prashant-shahi** [comment]
Hey @thunko!

Are you running `v0.43.0` version of OtelCollector using the operator?

If not, you should perhaps **upgrade** the exist helm release along with the following:
```
--set manager.image.tag=v0.43.0
```

Do let us know if it helps.

**Comment by thunko** [comment]
hi @prashant-shahi thanks for getting back

I'm running OtelCollector `0.46.0` from the operator (same version):
`Image:         ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.46.0`

Do you suggest to downgrade ?
Thank you,

**Comment by prashant-shahi** [comment]
@thunko yes, you would need to use `v0.43.0` since latest version of SigNoz OtelCollector supports that version.

URL of the version: https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fopentelemetry-operator/14805564?tag=v0.43.0

**Comment by thunko** [comment]
@prashant-shahi thank you

now using `0.43.0`: `Image:         otel/opentelemetry-collector:0.43.0` installed through [helm](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/opentelemetry-operator-0.6.2/charts/opentelemetry-operator/Chart.yaml)
but still unable to plot metrics.
Collectors in both ends looks cleear and `Ready to process data` but my PromQL query doesn't go through.
Trying to troubleshoot landed into these logs:

```
➜  ~ k -n platform logs my-release-signoz-query-service-0 -f
time="2022-04-22T15:48:29Z" level=warning msg="Ignoring hint {StepMs:60000 Func: StartMs:1650641908870 EndMs:1650642508870} for query [1650641908870,1650642508870,{__name__=\"k8s_container_memory_limit\"}]." component=clickhouse
```

which took me to the clickhouse-operator floded by the following error:
```
$ k -n platform logs clickhouse-operator-8cff468-zwj9n clickhouse-operator -f
E0422 15:48:21.661892       1 reflector.go:138] pkg/client/informers/externalversions/factory.go:117: Failed to watch *v1.ClickHouseInstallationTemplate: failed to list *v1.ClickHouseInstallationTemplate: the server could not find the requested resource (get clickhouseinstallationtemplates.clickhouse.altinity.com)
```
could be something wrong with the installation ? tried re-installing and got the same.

Any advice greatly appreciated.

**Comment by prashant-shahi** [comment]
@thunko Can you confirm if all of the SigNoz components are up with the following?
```
kubectl get all -n platform
```

I tested the same from [Kubernetes Infra Metrics docs](https://signoz.io/docs/tutorial/kubernetes-infra-metrics).
I was able the plot graph.

Can you make sure the k8s cluster is up?
Also, make sure that you have included appropriate SigNoz OtelCollector address in the files below: 
- agent/infra-metrics.yaml
- deployment/all-in-one.yaml

Can you join our Slack Community? We could get on Huddle to quickly resolve this.

**Comment by thunko** [comment]
@prashant-shahi they are all up

```
➜  ~ k -n platform get all
NAME                                                            READY   STATUS    RESTARTS   AGE
pod/chi-signoz-cluster-0-0-0                                    1/1     Running   0          2d17h
pod/clickhouse-operator-8cff468-9h75t                           2/2     Running   0          2d17h
pod/my-release-signoz-alertmanager-0                            1/1     Running   0          2d17h
pod/my-release-signoz-frontend-679745cc99-ns9lj                 1/1     Running   0          2d17h
pod/my-release-signoz-otel-collector-54d458dd8b-sthmc           1/1     Running   0          2d17h
pod/my-release-signoz-otel-collector-metrics-5dc97557f6-gcfsz   1/1     Running   0          2d17h
pod/my-release-signoz-query-service-0                           1/1     Running   0          2d17h
pod/my-release-zookeeper-0                                      1/1     Running   0          2d17h

NAME                                               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                                                AGE
service/chi-signoz-cluster-0-0                     ClusterIP   None           <none>        8123/TCP,9000/TCP,9009/TCP                                                             2d17h
service/clickhouse-operator-metrics                ClusterIP   10.3.146.236   <none>        8888/TCP                                                                               2d17h
service/my-release-clickhouse                      ClusterIP   10.3.157.31    <none>        8123/TCP,9000/TCP                                                                      2d17h
service/my-release-signoz-alertmanager             ClusterIP   10.3.104.240   <none>        9093/TCP                                                                               2d17h
service/my-release-signoz-alertmanager-headless    ClusterIP   None           <none>        9093/TCP                                                                               2d17h
service/my-release-signoz-frontend                 ClusterIP   10.3.129.12    <none>        3301/TCP                                                                               2d17h
service/my-release-signoz-otel-collector           ClusterIP   10.3.174.94    <none>        4317/TCP,4318/TCP,55680/TCP,55681/TCP,14250/TCP,14268/TCP,9411/TCP,8888/TCP,8889/TCP   2d17h
service/my-release-signoz-otel-collector-metrics   ClusterIP   10.3.237.96    <none>        4317/TCP,4318/TCP,55680/TCP,55681/TCP,14250/TCP,14268/TCP,9411/TCP,8888/TCP            2d17h
service/my-release-signoz-query-service            ClusterIP   10.3.205.205   <none>        8080/TCP                                                                               2d17h
service/my-release-zookeeper                       ClusterIP   10.3.144.187   <none>        2181/TCP,2888/TCP,3888/TCP                                                             2d17h
service/my-release-zookeeper-headless              ClusterIP   None           <none>        2181/TCP,2888/TCP,3888/TCP                                                             2d17h

NAME                                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/clickhouse-operator                        1/1     1            1           2d17h
deployment.apps/my-release-signoz-frontend                 1/1     1            1           2d17h
deployment.apps/my-release-signoz-otel-collector           1/1     1            1           2d17h
deployment.apps/my-release-signoz-otel-collector-metrics   1/1     1            1           2d17h

NAME                                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/clickhouse-operator-8cff468                           1         1         1       2d17h
replicaset.apps/my-release-signoz-frontend-679745cc99                 1         1         1       2d17h
replicaset.apps/my-release-signoz-otel-collector-54d458dd8b           1         1         1       2d17h
replicaset.apps/my-release-signoz-otel-collector-metrics-5dc97557f6   1         1         1       2d17h

NAME                                               READY   AGE
statefulset.apps/chi-signoz-cluster-0-0            1/1     2d17h
statefulset.apps/my-release-signoz-alertmanager    1/1     2d17h
statefulset.apps/my-release-signoz-query-service   1/1     2d17h
statefulset.apps/my-release-zookeeper              1/1     2d17h
```

what metrics did you try to plot ?
so you don't get the errors I posted in my previous comment ?

I defined the address in the `OpenTelemetryCollector` CR I posted in the description of this ticket: https://github.com/SigNoz/signoz/issues/1011#issue-1212210619

I joined slack, here is the thread in the support channel: https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1650618461342569

**Comment by prashant-shahi** [comment]
@thunko In the logs, I see both of those however, they shouldn't cause any issue.

From the looks of the OtelCollector config, I suppose you have missed out including `kubeletstats`. Also, make sure to include the receiver in the pipeline.

```yaml
      kubeletstats:
        collection_interval: 60s
        auth_type: "serviceAccount"
        endpoint: "${K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
```

If it still does not resolve your issue, don't hesitate to ping me on our Slack Community.
