### ISSUE TITLE
[web] nginx reverse proxy not working at subpath

### ISSUE THREAD

**Issue by ParamTechLead** [SigNoz/signoz#1236]
Hi, We are trying to run Signoz frontend behind nginx reverse proxy. When we try to access signoz using server path like https://domain.com/signoz only a blank page is displayed. We are able to access using root path and port. But in our case it needs to be under /signoz and not / .
How do we update baseref in helm values.yaml for frontend?

**Comment by sharif997** [comment]
Hi, Any updates on this ?

**Comment by luolong** [comment]
There is already an existing issue #357

**Comment by Nageshbansal** [comment]
Hi folks,
Base path support is live in SigNoz **v0.121.0**. You can now serve SigNoz under any URL prefix.

Check out the [Serving SigNoz on an external URL](https://signoz.io/docs/manage/administrator-guide/configuration/serving-on-external-url/) doc.

PS: We've also been building [Foundry](https://github.com/SigNoz/foundry), a unified install tool for SigNoz. Describe your deployment once in `casting.yaml` and `foundryctl` handles the rest, across Docker, Kubernetes, ECS, Render, Railway, and more. 

Here's how easy it is to set the  base path with Foundry:
```yaml
apiVersion: v1alpha1
metadata:
  name: signoz
spec:
  deployment:
    flavor: compose
    mode: docker
  signoz:
    spec:
      env:
        SIGNOZ_GLOBAL_EXTERNAL__URL: "https://example.com/signoz"
  ```                                             
  ```bash                                                                                                                         
  foundryctl cast -f casting.yaml
  ```
