### ISSUE TITLE
Alert Definitions Through Source Code

### ISSUE THREAD

**Issue by blakeromano** [SigNoz/signoz#1273]
## Is your feature request related to a problem?

This is a feature that the Prometheus Alertmanager comes with and I think would be super helpful for other teams as well as our own in terms of transitioning from Prometheus/Grafana to Signoz and Open Telemetry.

## Describe the solution you'd like

We'd like to see an option which may also work would be to support the scanning of github repos for a specific yaml file and maybe even a subsection within a yaml file. For example maybe alert manager could have the additional fields related to this feature. I think scanning would be ideal with a Github App. You could use the credentials of the github app to scan every five minutes or so and just rerun through all orgs/repos that the App has access to assuming it has permission to read the contents of the file specified in the `yamlFilePath` parameter you could process from there.

```yaml
sourceCodeAlerts:
  provider: github
  appId: 12345
  pemKey: "---KEY_START---\n_key_is_here\n---KEY_END---"
  yamlFilePath: "alerts.yaml" or "subfolder/alerts.yaml"
  sectionInYaml: "" (for no subsection) "global.alerts"
  url: "https://github.com"
  apiUrl: "https://api.github.com"
  webhookToken: "12345"
```
In the case there would be a sectionInYaml parameter the `alerts.yaml` could look something like this
```yaml
global:
  name: something
  alerts:
    - put alerts here
 ``` 

A more problematic but another option would be to see a Kubernetes CRD that can be consumed by the Signoz Alert manager and edit, add or delete alerts based on the `Signoz Alerts` CRD that are present. I think to support multiple clusters it would be nice to have a consumer that can collect all of the `Signoz Alerts` CRD, be able to make authenticated calls to the Signoz Alertmanager to update/add/delete alerts.

#### *Thank you* for your feature request – we love each and every one!
