### ISSUE TITLE
No Traces

### ISSUE THREAD

**Issue by iomari** [SigNoz/signoz#1451]
Greetings,
I'm running the signoz with the lateset opentelemetry-python v1.12.0rc2 in docker. Signoz is running with the demo I'm not getting traces from my sample python flask app. If I run:

`OTEL_RESOURCE_ATTRIBUTES=service.name="inspired" OTEL_EXPORTER_OTLP_ENDPOINT="localhost:4318" opentelemetry-instrument --traces_exporter otlp_proto_http,console flask run`

I see the output on the console but nothing shows on the Signoz frontend.

the python app:

```
from opentelemetry import trace
from opentelemetry.exporter.jaeger.thrift import JaegerExporter
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor, ConsoleSpanExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource

from random import randint
from flask import Flask, request
from time import sleep
from sys import exit

################# Metrics Start
from opentelemetry import metrics
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import (ConsoleMetricExporter, PeriodicExportingMetricReader,)

metric_reader = PeriodicExportingMetricReader(ConsoleMetricExporter())
provider = MeterProvider(metric_readers=[metric_reader])

# Sets the global default meter provider
metrics.set_meter_provider(provider)

# Creates a meter from the global meter provider
meter = metrics.get_meter(__name__)
################# Metrics end



# Service name is required for most backends,
# and although it's not necessary for console export,
# it's good to set service name anyways.
resource = Resource(attributes={
    SERVICE_NAME: "inspired"
})
'''
provider = TracerProvider()
trace.set_tracer_provider(provider)
tracer = trace.get_tracer(__name__)
'''
provider = TracerProvider(resource=resource)
processor = BatchSpanProcessor(ConsoleSpanExporter())
provider.add_span_processor(processor)
trace.set_tracer_provider(provider)
tracer = trace.get_tracer(__name__)

app = Flask(__name__)

@app.route("/roll")
def roll():
    sides = int(request.args.get('sides'))
    rolls = int(request.args.get('rolls'))
    sides = 6
    rolls = 1
    total = 0
    while True:
        with tracer.start_as_current_span("roll_sum01"):
            span = trace.get_current_span()
            sum01 = 0
            for r in range(0,1):
                result = randint(1,6)
                span.add_event( "log", {
                    "roll.sides": sides,
                    "roll.result": result,
                })
                sum01 += result
                total += result
            with tracer.start_as_current_span("roll_sum02"):
                span = trace.get_current_span()
                sum02 = 0
                for r in range(0,1):
                    result = randint(1,6)
                    span.add_event( "log", {
                        "roll.sides": sides,
                        "roll.result": result,
                    })
                    sum02 += result
                    total += result
                with tracer.start_as_current_span("roll_sum03"):
                    span = trace.get_current_span()
                    sum03 = 0
                    for r in range(0,1):
                        result = randint(1,6)
                        span.add_event( "log", {
                            "roll.sides": sides,
                            "roll.result": result,
                        })
                        sum03 += result
                        total += result
                    with tracer.start_as_current_span("roll_total"):
                        span = trace.get_current_span()
                        span.add_event( "log", {
                            "roll.total": total,
                        })
                        sleep(5)
        # return  str(f'{sum01},{sum02},{sum03}')

```
the otel-collector-config.yaml: 

```
receivers:
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:12345"
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4137"
      http:
        endpoint: "localhost:4138"
  jaeger:
    protocols:
      grpc:
      thrift_http:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s
  signozspanmetrics/prometheus:
    metrics_exporter: prometheus
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 50ms, 100ms, 250ms, 500ms, 1000ms, 1400ms, 2000ms, 5s, 10s, 20s, 40s, 60s ]
    dimensions_cache_size: 10000
    dimensions:
      - name: service.namespace
        default: default
      - name: deployment.environment
        default: default
  # memory_limiter:
  #   # 80% of maximum memory up to 2G
  #   limit_mib: 1500
  #   # 25% of limit up to 2G
  #   spike_limit_mib: 512
  #   check_interval: 5s
  #
  #   # 50% of the maximum memory
  #   limit_percentage: 50
  #   # 20% of max memory usage spike expected
  #   spike_limit_percentage: 20
  # queued_retry:
  #   num_workers: 4
  #   queue_size: 100
  #   retry_on_failure: true
extensions:
  health_check: {}
  zpages: {}
exporters:
  clickhousetraces:
    datasource: tcp://clickhouse:9000/?database=signoz_traces
  clickhousemetricswrite:
    endpoint: tcp://clickhouse:9000/?database=signoz_metrics
    resource_to_telemetry_conversion:
      enabled: true
  prometheus:
    endpoint: "0.0.0.0:8889"
service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [jaeger, otlp]
      processors: [signozspanmetrics/prometheus, batch]
      exporters: [clickhousetraces]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [clickhousemetricswrite]
    metrics/spanmetrics:
      receivers: [otlp/spanmetrics]
      exporters: [prometheus]

```
