### ISSUE TITLE
Docker Container fails to start if Clickhouse Server has timezone "Etc/UTC"

### ISSUE THREAD

**Issue by derN3rd** [SigNoz/signoz#1460]
## Bug description

If Clickhouse Server has timezone "Etc/UTC" the query-service will fail to start.

## Expected behavior

Should start with no issues

## How to reproduce

While testing out signoz with out own existing Clickhouse servers, I couldn't get it to launch, because of the issue

```
query-service             | 2022-08-01T11:05:14.944Z	INFO	version/version.go:43
query-service             |
query-service             | SigNoz version   : v0.10.0
query-service             | Commit SHA-1     : bf2f3f8
query-service             | Commit timestamp : 2022-07-16T09:45:46Z
query-service             | Branch           : HEAD
query-service             | Go version       : go1.17.12
query-service             |
query-service             | For SigNoz Official Documentation,  visit https://signoz.io/docs
query-service             | For SigNoz Community Slack,         visit http://signoz.io/slack
query-service             | For discussions about SigNoz,       visit https://community.signoz.io
query-service             |
query-service             | Licensed under the MIT License.
query-service             | Copyright 2022 SigNoz
query-service             |
query-service             |
query-service             | 2022-08-01T11:05:14.945Z	WARN	query-service/main.go:61	No JWT secret key is specified.
query-service             | main.main
query-service             | 	/go/src/github.com/signoz/signoz/pkg/query-service/main.go:61
query-service             | runtime.main
query-service             | 	/usr/local/go/src/runtime/proc.go:255
query-service             | 2022-08-01T11:05:15.257Z	INFO	app/server.go:84	Using ClickHouse as datastore ...
query-service             | 2022-08-01T11:05:15.261Z	ERROR	clickhouseReader/reader.go:102	failed to initialize ClickHouse: error connecting to primary db: could not load time location: unknown time zone Etc/UTC
query-service             | go.signoz.io/query-service/app/clickhouseReader.NewReader
query-service             | 	/go/src/github.com/signoz/signoz/pkg/query-service/app/clickhouseReader/reader.go:102
query-service             | go.signoz.io/query-service/app.NewServer
query-service             | 	/go/src/github.com/signoz/signoz/pkg/query-service/app/server.go:85
query-service             | main.main
query-service             | 	/go/src/github.com/signoz/signoz/pkg/query-service/main.go:66
query-service             | runtime.main
query-service             | 	/usr/local/go/src/runtime/proc.go:255

```

1. Pull the repo
2. Use docker setup script
3. Change configs to replace docker-clickhouse with existing clickhouse server
4. Start with docker-compose up
5. Startup will fail and logs are as shown above

## Version information 
* **Signoz version**: 0.10.0
* **Browser version**:
* **Your OS and version**: Ubuntu 22.04 AWS (`Linux ip-xxx 5.15.0-1011-aws #14-Ubuntu SMP Wed Jun 1 20:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* **Your CPU Architecture**(ARM/Intel): amd64

**Comment by derN3rd** [comment]
Seems to be the same issue as https://github.com/SigNoz/signoz/issues/1150

**Comment by derN3rd** [comment]
The fix was to not only add the [zoneinfo to the query-service](https://github.com/SigNoz/signoz/issues/1150#issuecomment-1200903779), but to the otel collector as well.

Why is the zoneinfo not on the main Dockerfile?
Was there a specific reason?

My fix:

my docker-compose.yaml
```yaml
version: "2.4"

services:
  alertmanager:
    image: signoz/alertmanager:0.23.0-0.1
    volumes:
      - ./data/alertmanager:/data
    depends_on:
      query-service:
        condition: service_healthy
    restart: on-failure
    command:
      - --queryService.url=http://query-service:8085
      - --storage.path=/data

  query-service:
    build:
      context: custom-signoz
      dockerfile: Dockerfile
    container_name: query-service
    command: ["-config=/root/config/prometheus.yml"]
    volumes:
      - ./prometheus.yml:/root/config/prometheus.yml
      - ../dashboards:/root/config/dashboards
      - ./data/signoz/:/var/lib/signoz/
    environment:
      - ClickHouseUrl=tcp://existing-clickhouse.internal.net:9000/?database=signoz_traces
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=false
      - DEPLOYMENT_TYPE=docker-standalone-amd
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8080/api/v1/version"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    image: signoz/frontend:0.10.0
    container_name: frontend
    restart: on-failure
    depends_on:
      - alertmanager
      - query-service
    ports:
      - "3301:3301"
    volumes:
      - ../common/nginx-config.conf:/etc/nginx/conf.d/default.conf

  otel-collector:
    build:
      context: custom-otel
      dockerfile: Dockerfile
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
    ports:
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP HTTP receiver
    mem_limit: 2000m
    restart: on-failure

  otel-collector-metrics:
    build:
      context: custom-otel
      dockerfile: Dockerfile
    command: ["--config=/etc/otel-collector-metrics-config.yaml"]
    volumes:
      - ./otel-collector-metrics-config.yaml:/etc/otel-collector-metrics-config.yaml
    restart: on-failure
```

custom-signoz/Dockerfile:
```
FROM golang:1.17.1-alpine3.14 AS builder

RUN apk --no-cache add tzdata zip ca-certificates
WORKDIR /usr/share/zoneinfo
RUN zip -r -0 /zoneinfo.zip .

# https://hub.docker.com/r/signoz/query-service/tags
FROM signoz/query-service:0.10.0

COPY --from=builder /zoneinfo.zip /zoneinfo.zip
ENV ZONEINFO=/zoneinfo.zip

ENTRYPOINT ["./query-service"]
CMD ["-config" "/root/config/prometheus.yml"]
```

custom-otel/Dockerfile:
```
FROM golang:1.17.1-alpine3.14 AS builder

RUN apk --no-cache add tzdata zip ca-certificates
WORKDIR /usr/share/zoneinfo
RUN zip -r -0 /zoneinfo.zip .

FROM signoz/otelcontribcol:0.45.1-1.1

COPY --from=builder /zoneinfo.zip /zoneinfo.zip
ENV ZONEINFO=/zoneinfo.zip

ENTRYPOINT ["/otelcontribcol"]
CMD ["--config" "/etc/otel/config.yaml"]
```
