### ISSUE TITLE
Docker container name not present in docker container logs.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#1597]
Right now the default docker log collection doesn't have the container name in attributes.

**Comment by nityanandagohain** [comment]
Solution using [logsprout](https://github.com/gliderlabs/logspout) .

We can route the logs to signoz otel collector from logsprout and we can get the container id as well.

The configuration for it is
```
receivers:
  .........
  tcplog:
    listen_address: "0.0.0.0:2255"
    attributes: {}
    add_attributes: false
    operators:
      - type: regex_parser
        regex: '^<(?P<priority>[0-9]+)>[0-9]+ (?P<timestamp>[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?) (?P<container_id>\S+) (?P<container_name>\S+) [0-9]+ - - (?P<body>.*)'
      - type: move
        from: attributes["body"]
        to: body
      - type: time_parser
        parse_from: attributes.timestamp
        # layout: '%Y-%m-%dT%H:%M:%SZ'
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      - type: remove
        field: attributes.timestamp
.....
service:
  pipelines:
    .........
    logs:
      receivers: [tcplog, otlp]
      processors: [batch]
      exporters: [clickhouselogsexporter]
```

We will also need to export  `2255` port for otel collector.


Now we can start logspout by running
```
docker run --net=host --rm --name="logspout" \
        --volume=/var/run/docker.sock:/var/run/docker.sock \
        gliderlabs/logspout \
        syslog+tcp://0.0.0.0:2255
```

We will be able to see the attributes in the UI

![Screenshot 2022-09-27 at 2 44 52 PM](https://user-images.githubusercontent.com/26831659/192488764-8f78d656-53e2-47ce-8d6b-18446126e737.png)
