### ISSUE TITLE
Easy way to configure application healthcheck endpoint

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1682]
support to configure application healthcheck endpoint if it fails to reach it will raise slack notification.
Please let me know if this is possible.

[Slack Message](https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1667381638887299?thread_ts=1667381638.887299&cid=C01HWQ1R0BC)

**Comment by srikanthccv** [comment]
The `httpcheck` (will be shipped soon with our distro) can be used for this. They need to add the receiver with an endpoint and collection interval.
```
receivers:
  httpcheck:
    endpoint: http://host.docker.internal:5002/health
    method: GET
    collection_interval: 10s
```

And include it in the metrics pipeline.
```
...
    metrics:
      receivers: [otlp, httpcheck]
      processors: [batch]
      exporters: [clickhousemetricswrite]
```

There will be a metric named `httpcheck_status` whose value is either 0 or 1 if the endpoint is healthy. The alerts can be set on this metric as they like. If they have complex use cases they can go with blackbox exporter.
