### ISSUE TITLE
Long response time in Traces due to Signoz Frontend UX facet selection

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#1689]
## In what situation are you experiencing subpar performance?
Anytime traces are opened even for smaller time ranges

## How to reproduce
Bit complex to describe, here's the video: https://drive.google.com/file/d/1nq-Dw1saRGkDWAgJf25IoovN2uKJfXXO/view?usp=share_link
## Suggestion
1. Have `Status Code`, `Status` and `HTTP Method` hardcoded as filters instead of facets so that we can always select from them
2. Have `service name` something that we can type as well on Clear all selection

**Comment by pranay01** [comment]
@abhinavramana Can you share details on how much RAM/CPU have you allocated to SigNoz, and how many traces/data are you querying on?

**Comment by abhinavramana** [comment]
This is the cluster setup:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: signoz-prod
  region: us-east-1
  version: "1.22"

nodeGroups:
  - name: signoz-prod-ng-bigger
    instanceType: m5.8xlarge
    volumeSize: 100
    desiredCapacity: 4  
```

And 

```
global:
  storageClass: gp2-resizable

otelCollector:
  service:
    type: LoadBalancer
  replicaCount: 3

k8s-infra:
  enabled: false

frontend:
  service:
    type: LoadBalancer

clickhouse:
  cloud: aws
  installCustomStorageClass: true
  persistence:
    size: 1000Gi
```
