### ISSUE TITLE
resourcedetection processor context not being saved to clickhouse metrics

### ISSUE THREAD

**Issue by ttaghavi** [SigNoz/signoz#1818]
As a disclaimer, I just starting using signoz and otel, so it could very well be a misconfiguration issue on my part. 

## Bug description

Using the [resourcedetection processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor), I am unable to set any context for metric data being saved to clickhouse 

## Expected behavior

The resource context (host_name, os_type) should appear in the clickhouse database under labels

## How to reproduce

Here my current setup (everything local).

1. Bringing up signoz stack with following docker compose configuration (default config minus the `otel-collector-metrics`, `hotrod` and `load-hotrod` services)

```
version: "2.4"                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.8.8-alpine
    # ports:
    # - "9000:9000"
    # - "8123:8123"
    tty: true
    volumes:
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse-users.xml:/etc/clickhouse-server/users.xml
      # - ./clickhouse-storage.xml:/etc/clickhouse-server/config.d/storage.xml
      - ./data/clickhouse/:/var/lib/clickhouse/
    restart: on-failure
    logging:
      options:
        max-size: 50m
        max-file: "3"
    healthcheck:
      # "clickhouse", "client", "-u ${CLICKHOUSE_USER}", "--password ${CLICKHOUSE_PASSWORD}", "-q 'SELECT 1'"
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  alertmanager:
    image: signoz/alertmanager:0.23.0-0.2
    volumes:
      - ./data/alertmanager:/data
    depends_on:
      query-service:
        condition: service_healthy
    restart: on-failure
    command:
      - --queryService.url=http://query-service:8085
      - --storage.path=/data

# Notes for Maintainers/Contributors who will change Line Numbers of Frontend & Query-Section. Please Update Line Numbers in `./scripts/commentLinesForSetup.sh` & `./CONTRIBUTING.md`

  query-service:
    image: signoz/query-service:0.11.4
    container_name: query-service
    command: ["-config=/root/config/prometheus.yml"]
    # ports:
    #   - "6060:6060"     # pprof port
    #   - "8080:8080"     # query-service port
    volumes:
      - ./prometheus.yml:/root/config/prometheus.yml
      - ../dashboards:/root/config/dashboards
      - ./data/signoz/:/var/lib/signoz/
    environment:
      - ClickHouseUrl=tcp://clickhouse:9000/?database=signoz_traces
      - ALERTMANAGER_API_PREFIX=http://alertmanager:9093/api/
      - SIGNOZ_LOCAL_DB_PATH=/var/lib/signoz/signoz.db
      - DASHBOARDS_PATH=/root/config/dashboards
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8080/api/v1/version"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      clickhouse:
        condition: service_healthy

  frontend:
    image: signoz/frontend:0.11.4
    container_name: frontend
    restart: on-failure
    depends_on:
      - alertmanager
      - query-service
    ports:
      - "3301:3301"
    volumes:
      - ../common/nginx-config.conf:/etc/nginx/conf.d/default.conf

  otel-collector:
    image: signoz/signoz-otel-collector:0.63.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    user: root # required for reading docker container logs
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
    ports:
      # - "1777:1777"     # pprof extension
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP HTTP receiver
      # - "8888:8888"     # OtelCollector internal metrics
      # - "8889:8889"     # signoz spanmetrics exposed by the agent
      # - "9411:9411"     # Zipkin port
      # - "13133:13133"   # health check extension
      # - "14250:14250"   # Jaeger gRPC
      # - "14268:14268"   # Jaeger thrift HTTP
      # - "55678:55678"   # OpenCensus receiver
      # - "55679:55679"   # zPages extension
    restart: on-failure
    depends_on:
      clickhouse:
        condition: service_healthy
```
Here the `otel-collector-config.yaml`:

```
receivers:                                                                                                                                                                                                                                    
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
      
processors:
  batch:
    send_batch_size: 10000
    send_batch_max_size: 11000                                                                                         
    timeout: 10s                                                                                                       
      
exporters:
  clickhousetraces:                                                                                                    
    datasource: tcp://clickhouse:9000/?database=signoz_traces                                                          
    
  clickhousemetricswrite:                                                                                              
    endpoint: tcp://clickhouse:9000/?database=signoz_metrics                                                           
                                                                                                                       
  clickhouselogsexporter:                                                                                              
    dsn: tcp://clickhouse:9000/
    timeout: 5s
    sending_queue:
      queue_size: 100                                                                                                  
    retry_on_failure:                                                                                                  
      enabled: true
      initial_interval: 5s                                                                                             
      max_interval: 30s                                                                                                
      max_elapsed_time: 300s                                                                                           
      
service:                                                                                                               
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhousetraces]                                                                                    
    metrics:
      receivers: [otlp]                                                                                                
      processors: [batch]
      exporters: [clickhousemetricswrite]                                                                              
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouselogsexporter]
```

2. Starting a docker container running the `otel/opentelemetry-collector-contrib:0.66.0` image with following command:

``` 
docker run \
  -v $(pwd)/config.yaml:/etc/otelcol-contrib/config.yaml \
  -v /:/hostfs \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -p 0.0.0.0:54527:54527/tcp \
  otel/opentelemetry-collector-contrib:0.66.0
```

Here the `config.yaml` for this container:

```
receivers:
  hostmetrics:
    collection_interval: 10s
    root_path: /hostfs
    scrapers:
      load: {}

  syslog:
    tcp:
      listen_address: "0.0.0.0:54527"
    protocol: rfc3164
    location: UTC
    operators:
      - type: move
        from: attributes.message
        to: body

processors:
  batch:
    send_batch_size: 1000
    timeout: 1s
                                                                                                                                                                                                                                              
  resourcedetection:
    detectors: [docker, env]
    timeout: 2s
    override: false
  
exporters:
  otlp:
    endpoint: 192.168.1.47:4317
    tls:
      insecure: true

  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection, batch]
      exporters: [otlp]
  
    logs:
      receivers: [syslog]
      processors: [resourcedetection, batch]
      exporters: [otlp]
```

3. rsyslog was configured according to this article: https://signoz.io/docs/userguide/collecting_syslogs/

4. The clickhouse DB is receiving logs and metrics. Looking at the data, the logs have context, but not the metrics:

```
dabf3b5e3c3f :) select * from signoz_logs.logs limit 1\G

SELECT *
FROM signoz_logs.logs
LIMIT 1

Query id: fa798ada-f5d1-418b-b0e2-03b431d3cbeb

Row 1:
──────
timestamp:                1670326695000000000
observed_timestamp:       1670323095350083091
id:                       2IXLVZ5u9kIcqwX24q7fXIA0gNe
trace_id:                 
span_id:                  
trace_flags:              0
severity_text:            info
severity_number:          9
body:                     Joining mDNS multicast group on interface veth01247bf.IPv6 with address fe80::d496:2ff:fe42:216.
resources_string_key:     ['host_name','os_type']
resources_string_value:   ['firemonkey','linux']
attributes_string_key:    ['hostname','proc_id','appname']
attributes_string_value:  ['firemonkey','1114','avahi-daemon']
attributes_int64_key:     ['facility','priority']
attributes_int64_value:   [3,30]
attributes_float64_key:   []
attributes_float64_value: []
```

```
dabf3b5e3c3f :) select * from signoz_metrics.time_series_v2 limit 1\G

SELECT *
FROM signoz_metrics.time_series_v2
LIMIT 1

Query id: 82cfa8f0-7726-4291-bfdb-46eef44325be

Row 1:
──────
metric_name:  system_cpu_load_average_15m
fingerprint:  10345722606695730287
timestamp_ms: 1670323105697
labels:       {"__name__":"system_cpu_load_average_15m"}
```

## Version information 

* **Signoz version**: Release/v0.11.4 (commit `18d80d47e5ad3f68220e84e509fa493f7ff20a26`)
* **Browser version**: not relevant
* **Your OS and version**: Linux Mint 21 Vanessa
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by ttaghavi** [comment]
Mis-configuration as I feared, closing the issue =)

Here the missing config:

```
   clickhousemetricswrite:
     endpoint: tcp://clickhouse:9000/?database=signoz_metrics
     resource_to_telemetry_conversion:
       enabled: true
```
