### ISSUE TITLE
Add support to http/https Proxy

### ISSUE THREAD

**Issue by paulohmorais** [SigNoz/signoz#2025]
## Is your feature request related to a problem?

Yes. Im using signoz installed with helm chart on kubernetes at GCP. On my company we need to use proxy to use internet. So after i try to configure alert channel on slack. I see they use hooks.slack.com. So i need to use proxy to work.
I made some trys with my hand, changing the charts of frontend, queryservice and alertmanager. To add this environments on pods: 
```
- name: HTTPS_PROXY
   value: "http://myproxy/"
- name: HTTP_PROXY
   value: "http://myproxy/"
- name: NO_PROXY
  value:  "noproxysList"
```

But i think we have alot things to put on NO_PROXY list. And this, is a hard workaround to make Proxy works fine on signoz.               

## Describe the solution you'd like

Develop native support for proxy on signoz.

## Describe alternatives you've considered

A documentation saying who configure all pods that need this proxys envs and the all NO_PROXY configuration to signoz works well.

ps: I dont have success on my trys, but i think i am almost, After add NO_PROXY to alert-manager pod.

**Comment by davisagli** [comment]
I have a similar requirement to send notifications to a Slack webhook via a proxy, but I am using Docker Swarm. I tried modifying /etc/alertmanager/alertmanager.yml inside the signoz/alertmanager container to set `http_config.proxy_url`, but alertmanager is still not connecting via the proxy.

**Comment by pranay01** [comment]
@mindhash Do you have more insights on this?

**Comment by ayush-rathore-quartic** [comment]
@pranay01 @paulohmorais @mindhash @davisagli We are facing the same issue, Any work around for this would be greatly appreciated, Did anyone find it?

**Comment by Sinhyeok** [comment]
@mindhash 
Even after setting the HTTP_PROXY environment variable in the Alertmanager pod and enabling proxy_from_environment: true in the alertmanager.yaml configuration, the proxy settings are not being applied to the requests.

```yaml
  alertmanager:
    replicaCount: 1
    additionalEnvs:
      HTTP_PROXY: http://sample.com:3333
      http_proxy: $(HTTP_PROXY)
      HTTPS_PROXY: http://sample.com:3333
      https_proxy: $(HTTPS_PROXY)
      NO_PROXY: "localhost,127.0.0.1,127.0.0.0/8"
      no_proxy: $(NO_PROXY)
    config:
      global:
        http_config:
          proxy_url: http://sample.com:3333
          no_proxy: "localhost,127.0.0.1,127.0.0.0/8"
          proxy_from_environment: true
```
