### ISSUE TITLE
Ability to set endpoint monitoring from UI

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#2293]
Suggestion from slack community

```
receivers:
  httpcheck/endpoint1:
    endpoint: https://uri/....
    method: GET
    collection_interval: 5s
```

this specific case should probably have an interface in the app that writes this configurations and a button to restart the service

this will give immediate value to your product without any "coding" required, just deploying and setting up endpoints
