### ISSUE TITLE
Missing labels when add an exporter

### ISSUE THREAD

**Issue by wangchaoforever** [SigNoz/signoz#2602]
## In what situation are you experiencing subpar performance?

When an exporter is added, the label is missing from the labels field in the table signoz_metrics.time_series_v2

## How to reproduce

1.Add an exporter
```yaml
        - job_name: mysql-test
          scrape_interval: 30s
          honor_labels: false
          static_configs:
            - targets: ['172.26.94.130:9104']
              labels:
                job_name: mysql-test
                instance: mysqltest01
```
2.When an exporter is added, i can get the label `job_name` in the table signoz_metrics.time_series_v2. But can not get label `instance`.Data like this:
```sql
{"__name__":"mysql_info_schema_innodb_cmpmem_relocation_time_seconds_total","buffer_pool":"3","job_name":"mysql-test","page_size":"16384"}
```

## Your Environment

- [X] Linux
- [ ] Mac
- [ ] Windows

CentOS Linux release 7.9.2009 (Core)
