### ISSUE TITLE
signoz-clickhouse PV requires pruning when helm chart deployed via Argo CD

### ISSUE THREAD

**Issue by AurimasNav** [SigNoz/signoz#2630]
## Bug description

When deploying helm chart via Argo CD, resulting application has a persistent volume deployed from volumeClaimTemplate ` data-volumeclaim-template-chi-signoz-clickhouse-cluster-0-0-0`, Argo CD is unable to identify parent reference and tries to delete as it seems not to be a part of the application deployment.

![image](https://user-images.githubusercontent.com/7810047/234297765-4fbbbbba-dfb8-4b28-99f4-7ddafde42ac3.png)

## Expected behavior

Application deployed with no OutOfSync resources.

## How to reproduce

deploy signoz helm chart 0.14.1 with default helm values

1. kustomization.yaml @ https://dev.azure.com/org/proj/_git/k8s-signoz main branch

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: signoz
resources: []

helmGlobals:
  chartHome: charts
helmCharts:
- name: signoz
  version: 0.14.1
  repo: https://charts.signoz.io
  releaseName: signoz
  namespace: signoz
  includeCRDs: true
  valuesFile: values.yaml
```
2. values.yaml @ https://dev.azure.com/org/proj/_git/k8s-signoz main branch

```yaml
#empty
```

3. application.yaml

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: /
    repoURL: https://dev.azure.com/org/pro>/_git/k8s-signoz
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions:
    - .spec.versions[].additionalPrinterColumns[]
```

4. `kubectl apply -f application.yaml`

## Version information 
* **Signoz version**: 0.18.2 (helm chart 0.14.1)

## Additional context
AKS 1.26.3

Solving #2180 could as well solve this.

**Comment by AurimasNav** [comment]
A possible solution is  to provision additional resource:
```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseOperatorConfiguration
metadata:
  name: signoz-clickhouse-argocd-pv-nomanage
  namespace: signoz
spec:
  excludeFromPropagationLabels: ["app.kubernetes.io/instance", "argocd.argoproj.io/instance"]
  label:
    exclude: ["app.kubernetes.io/instance", "argocd.argoproj.io/instance"]
```

This issue is already raised here - https://github.com/SigNoz/charts/issues/86, but since this one has reproduction steps, maybe it is worth keeping around.
