### ISSUE TITLE
Unexpected "Not found's"

### ISSUE THREAD

**Issue by jdnurmi** [SigNoz/signoz#2885]
## Bug description

We've been testing with signoz (helm, eks) and things have largely worked well, but there are occasions - more frequent than I'm comfortable with, that things result in "Not found" pages/widgets.

Specifically, I see it either in the 'graph' when loading logs, or after clicking on a specific exception from the exceptions list.  In both cases, typically hitting reload resolves the issue, so I _suspect_ it's an issue with our clickhouse installation,but I'm not sure how to proceed in debugging/resolving.

## Expected behavior

There's always logs, the chart should never be 'not found', and the exceptions list lists exceptions that it has seen, no exception should ever be 'not found'.

## How to reproduce

No idea - I can reproduce it frequently, but not reliably, as I said - hitting reload typically resolves it.  No obvious errors are logged or returned/bubbled up, but I'm happy to fetch any logs/data required.  On the 'exceptions' side, the return from the request is:

```
{"status":"error","errorType":"not_found","error":"Error/Exception not found"}
```
I've not had dev tools open when the logs dashboard fails to load, so cannot provide that result.

## Version information 
* **Signoz version**: 0.19 -> 0.22.2
* **Browser version**: Firefox 113.0.2
* **Your OS and version**: (Browser) Windows; (Signoz); AWS / Bottlerocket / EKS
* **Your CPU Architecture**(ARM/Intel): Intel

## Additional context

Early on in our experiments, we decided to expand our clickhouse installation to a 2x2 setup rather than the default singleton:

```
clickhouse:
  enabled: true
  serviceAccount:
    create: true
    name: signoz-clickhouse
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.account_id }}:role/signoz-clickhouse
#  # service:
#  #  annotations: {}
  persistence:
    enabled: true
    storageClass: gp2
    accessModes:
    - ReadWriteOnce
    size: 100Gi
  settings:
    prometheus/endpoint: /metrics
    prometheus/port: 9363
    prometheus/metrics: true
    prometheus/events: true
    prometheus/asynchronous_metrics: true
  podAnnotations:
    signoz.io/scrape: 'true'
    signoz.io/port: '9363'
    signoz.io/path: /metrics
  layout:
    shardsCount: 2
    replicasCount: 2
  coldStorage:
    # -- Whether to enable S3 cold storage
    enabled: true
    type: s3
    endpoint: REDACTED
    role:
      enabled: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.account_id }}:role/signoz-clickhouse
```

And never felt like things were "happy" after that expansion - so it's quite possible there's something inconsistent in some metadata/management tables that are beyond our clickhouse expertise.  All the nodes do in fact seem utilized, so it's not failing to distribute data, but perhaps some resync process needs to be retriggered:

```
$ for i in 0 1; do for j in 0 1; do kubectl exec -n monitoring chi-signoz-clickhouse-cluster-$i-$j-0 -- df /var/lib/clickhouse; done; done
Defaulted container "clickhouse" out of: clickhouse, signoz-clickhouse-udf-init (init)
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/nvme3n1         103019448  19536836  83466228  19% /var/lib/clickhouse
Defaulted container "clickhouse" out of: clickhouse, signoz-clickhouse-udf-init (init)
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/nvme4n1         103019448  20067504  82935560  19% /var/lib/clickhouse
Defaulted container "clickhouse" out of: clickhouse, signoz-clickhouse-udf-init (init)
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/nvme4n1         103019448  19289960  83713104  19% /var/lib/clickhouse
Defaulted container "clickhouse" out of: clickhouse, signoz-clickhouse-udf-init (init)
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/nvme5n1         103019448  20257064  82746000  20% /var/lib/clickhouse
```

Happy to retrieve any additional logs / data as desired.
