### ISSUE TITLE
Documentation on how to change the base path in the frontend for contacting the backend

### ISSUE THREAD

**Issue by svsk417** [SigNoz/signoz#3001]
## Is your feature request related to a problem?

I am currently investigating whether we can use SigNoz for our solution. 
We have an architecture as follows: 
![signoz_reverse_proxy](https://github.com/SigNoz/signoz/assets/60423321/541d1b41-49e0-4d7d-a827-6147e6e6cdb9)
The problem is, that I do not know how I can change the base path with which the fronend contacts the backend. I.e. I want to prepend `/signoz-api/`.

## Describe the solution you'd like

A hint on where I find the documentation or a hint on how to achieve this would be cool. Thank you in advance! 

## Describe alternatives you've considered

Cloning the repository and change it in the code rather than provide it as a docker environment variable or similar.

#### *Thank you* for your feature request – we love each and every one!

**Comment by therealpandey** [comment]
Duplicate of https://github.com/SigNoz/signoz/issues/357

**Comment by Nageshbansal** [comment]
Hi folks,
Base path support is live in SigNoz **v0.121.0**. You can now serve SigNoz under any URL prefix.

Check out the [Serving SigNoz on an external URL](https://signoz.io/docs/manage/administrator-guide/configuration/serving-on-external-url/) doc.

PS: We've also been building [Foundry](https://github.com/SigNoz/foundry), a unified install tool for SigNoz. Describe your deployment once in `casting.yaml` and `foundryctl` handles the rest, across Docker, Kubernetes, ECS, Render, Railway, and more. 

Here's how easy it is to set the  base path with Foundry:
```yaml
apiVersion: v1alpha1
metadata:
  name: signoz
spec:
  deployment:
    flavor: compose
    mode: docker
  signoz:
    spec:
      env:
        SIGNOZ_GLOBAL_EXTERNAL__URL: "https://example.com/signoz"
  ```                                             
  ```bash                                                                                                                         
  foundryctl cast -f casting.yaml
  ```
