### ISSUE TITLE
All in One Docker Image like jaegertracing/all-in-one

### ISSUE THREAD

**Issue by YutaUra** [SigNoz/signoz#3141]
## Is your feature request related to a problem?

Slightly cumbersome setup

## Describe the solution you'd like

For example, it would be very convenient if the setup could be done simply by writing the following (Of course, this is only for local startup, but it would greatly reduce the hurdles.)

```yaml
# compose.yml
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
```
