### ISSUE TITLE
Access frontend from a different basepath than root

### ISSUE THREAD

**Issue by ChronoDK** [SigNoz/signoz#357]
## Is your feature request related to a problem?

I'm behind an argo tunnel and traefik, and I need the frontend to be accessed from "http://siteurl/admin/signoz". Right now, this results in 404 errors.

## Describe the solution you'd like

Add an environment variable that changes the base path of the frontend. This is very common, and for instance Jaeger does this with "--query.base-path=/admin/jaeger".

## Additional context
Here is how I would like my docker-compose to look:

```
  signoz-frontend:
    image: signoz/frontend:0.4.3
    container_name: frontend
    depends_on:
      - query-service
    links:
      - "query-service"
    ports:
      - "3000:3000"
    volumes:
      - ./signoz/nginx-config.conf:/etc/nginx/conf.d/default.conf
    environment:
      - BASE_PATH=/admin/signoz
    labels:
      - traefik.enable=true
      - traefik.http.routers.signoz.rule=PathPrefix(`/admin/signoz`)
      - traefik.http.services.signoz.loadbalancer.server.port=3000

  traefik:
    image: traefik:latest
    ports:
      - 80:80
      - 8181:8080 #traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--log.level=ERROR"
      - "--api=true" #traefik dashboard
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
```

**Comment by tarunlalwani** [comment]
+1 on this. This should not be a `enterprise` only feature

**Comment by ankitnayan** [comment]
@tarunlalwani we are building our philosophy on what to include under the `community` and `enterprise` section at https://signoz.notion.site/Our-Philosophy-on-Pricing-73f5e6939c1f42be905fe937b4107dad

**Comment by luolong** [comment]
@tarunlalwani It would help if the page you referenced here, would be visible to the public. 
At the moment I understand that there is some unnamed criteria for assinging "enterprise" label to the feature that is written down in an internal wiki somewhere, but the reasoning is still opaque.

**Comment by luolong** [comment]
For what its worth, the feature is still sorely needed. 

As it stands now, signoz requires its own separate domain to run alongside of whatever app anyone is trying to observe.
Which might not be quite as easy to set up to a small units without administrative access to DNS. Or might not be desirable because of other concerns.

Technically, the problem is a misconfigured script path in the `index.html` file, packaged in the frontend container. Simply removing leading slash from these two lines would be enough:

```html
<script defer="defer" src="/runtime~main.91aa7fc1c78d08f032d4.js"></script>
<script defer="defer" src="/main.d449dea37fa3217c5f76.js"></script>
```

**Comment by jochenseeber** [comment]
This is kind of a deal breaker and not a feature that would make me pay for Signoz...

**Comment by ankitnayan** [comment]
our team might want to look at this again if we would like to give this to OSS as we have not put this in enterprise plan yet

**Comment by EinavDanielDX** [comment]
Really looking forward to this feature being available. A lot of deployments (mine included) sit behind a reverse proxy with path-based routing, and without a configurable base path the UI ends up breaking on redirects and static assets. 

Having a way to set this (env var / chart value) so SigNoz can run under something like `/observe/` or `/signoz/` would make things much easier to run alongside other services.

**Comment by akhiljavelin** [comment]
Any ETA for this ?. We would love to have a path-based routing config instead of having a dedicated subdomain for Signoz.

If we can configure this from the env in the helm values file (`example: https://common.domain.example/signoz`), then this will give more flexibility in the deployment

**Comment by therealpandey** [comment]
The work is actively in progress here https://github.com/SigNoz/signoz/pull/10926

**Comment by Nageshbansal** [comment]
Hi folks,
Base path support is live in SigNoz **v0.121.0**. You can now serve SigNoz under any URL prefix.

Check out the [Serving SigNoz on an external URL](https://signoz.io/docs/manage/administrator-guide/configuration/serving-on-external-url/) doc.

PS: We've also been building [Foundry](https://github.com/SigNoz/foundry), a unified install tool for SigNoz. Describe your deployment once in `casting.yaml` and `foundryctl` handles the rest, across Docker, Kubernetes, ECS, Render, Railway, and more. 

Here's how easy it is to set the  base path with Foundry:
```yaml
apiVersion: v1alpha1
metadata:
  name: signoz
spec:
  deployment:
    flavor: compose
    mode: docker
  signoz:
    spec:
      env:
        SIGNOZ_GLOBAL_EXTERNAL__URL: "https://example.com/signoz"
  ```                                             
  ```bash                                                                                                                         
  foundryctl cast -f casting.yaml
  ```
