### ISSUE TITLE
Cannot send traces using HTTP port 4318 to otel-collector

### ISSUE THREAD

**Issue by laurentpierson** [SigNoz/signoz#3684]
## Bug description

Traces sent using HTTP to otel-collector via port 4318 don't show up in Signoz

## How to reproduce

- I've installed SigNoz v0.30.0 on a remote Ubuntu VM, all containers are up, hot-rod application is correctly pushing traces to Signoz
- I've instrumented a locally deployed Spring Boot app, traces are also showing in Signoz
- But any attemp to push traces using HTTP from a browser doesn't show anything in Signoz
- I've used the Sample Angular App https://github.com/SigNoz/sample-angular-app/, traces are seemingly sent without error, e.g.
  - POST http://10.0.0.1:4318/v1/traces
  - Payload:
  `{"resourceSpans":[{"resource":{"attributes":[{"key":"test","value":{"stringValue":"test"}},{"key":"service.name","value":{"stringValue":"Angular Sample App"}},{"key":"telemetry.sdk.language","value":{"stringValue":"webjs"}},{"key":"telemetry.sdk.name","value":{"stringValue":"opentelemetry"}},{"key":"telemetry.sdk.version","value":{"stringValue":"1.0.1"}}],"droppedAttributesCount":0},"instrumentationLibrarySpans":[{"spans":[{"traceId":"de31b6a9e113dfc71bce0fb7b128f9b7","spanId":"45bcba57999d5d39","name":"HTTP PUT","kind":3,"startTimeUnixNano":1696680450436300000,"endTimeUnixNano":1696680452800100000,"attributes":[{"key":"http.method","value":{"stringValue":"PUT"}},{"key":"http.url","value":{"stringValue":"http://localhost:5555"}},{"key":"http.host","value":{"stringValue":"localhost:5555"}},{"key":"http.scheme","value":{"stringValue":"http"}},{"key":"http.target","value":{"stringValue":"/"}},{"key":"http.user_agent","value":{"stringValue":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"}},{"key":"http.status_code","value":{"intValue":0}}],"droppedAttributesCount":0,"events":[{"timeUnixNano":1696680452799800000,"name":"exception","attributes":[{"key":"exception.type","value":{"stringValue":"HttpErrorResponse"}},{"key":"exception.message","value":{"stringValue":"Http failure response for http://localhost:5555: 0 Unknown Error"}},{"key":"exception.stacktrace","value":{"kvlistValue":{"values":[{"key":"isTrusted","value":{"boolValue":true}}]}}}],"droppedAttributesCount":0}],"droppedEventsCount":0,"status":{"code":2},"links":[],"droppedLinksCount":0}],"instrumentationLibrary":{"name":"@jufab/opentelemetry-angular-interceptor","version":"1.0.1"}}]}]}`

  - Response: 
  - `200 OK`
  - `{"partialSuccess":{}}`

- I've also added CORS whitelisting in `otel-collector-config.yaml`
``` otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://localhost:4200
 ```

-  Troubleshooting collector endpoint on port 4317 (gRPC) works fine:
 ```
root@xxx~/docker/signoz/deploy/docker/clickhouse-setup# docker run -it --rm signoz/troubleshoot checkEndpoint -- 
 endpoint=10.0.0.1:4317
  2023-10-07T12:19:48.671Z        INFO    troubleshoot/main.go:28 STARTING!
  2023-10-07T12:19:48.672Z        INFO    checkEndpoint/checkEndpoint.go:41       checking reachability of SigNoz endpoint
  2023-10-07T12:19:48.677Z        INFO    troubleshoot/main.go:46 Successfully sent sample data to signoz ...
```
-  Troubleshooting collector endpoint on port 4318 (HTTP) show connection refused (maybe that troubleshooting tool isn't mean to test HTTP protocol?)

 ```
root@xxx:~/docker/signoz/deploy/docker/clickhouse-setup# docker run -it --rm signoz/troubleshoot checkEndpoint -- 
 endpoint=10.0.0.1:4318
  2023-10-07T12:21:31.151Z        INFO    troubleshoot/main.go:28 STARTING!
  2023-10-07T12:21:31.151Z        INFO    checkEndpoint/checkEndpoint.go:41       checking reachability of SigNoz endpoint
  Error: not able to send data to SigNoz endpoint ...
  rpc error: code = Unavailable desc = connection closed before server preface received
  Usage:
    signoz checkEndpoint [flags]

  Examples:
  checkEndpoint -e localhost:4317

Flags:
  -e, --endpoint string   URL to SigNoz with port
  -h, --help              help for checkEndpoint
 ```

- `docker-compose.yaml` is untouched, exposing both ports 4317 & 4318 for otel-collector

```
  otel-collector:
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-0.79.7}
    container_name: signoz-otel-collector
    command:
      [
        "--config=/etc/otel-collector-config.yaml",
        "--feature-gates=-pkg.translator.prometheus.NormalizeName"
      ]
    user: root # required for reading docker container logs
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
      - DOCKER_MULTI_NODE_CLUSTER=false
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
      - OTEL_TRACES_EXPORTER=console
    ports:
      # - "1777:1777"     # pprof extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      # - "8888:8888"     # OtelCollector internal metrics
      # - "8889:8889"     # signoz spanmetrics exposed by the agent
      # - "9411:9411"     # Zipkin port
      # - "13133:13133"   # health check extension
      # - "14250:14250"   # Jaeger gRPC
      # - "14268:14268"   # Jaeger thrift HTTP
      # - "55678:55678"   # OpenCensus receiver
      # - "55679:55679"   # zPages extension
    restart: on-failure
    <<: *clickhouse-depend
```

- `docker compose ps` shows

```
root@xxx:~/docker/signoz/deploy/docker/clickhouse-setup# docker compose ps
NAME                            IMAGE                                        COMMAND
                 SERVICE                  CREATED          STATUS                    PORTS
signoz-alertmanager             signoz/alertmanager:0.23.4                   "/bin/alertmanager --queryService.url=http://query-service:8085 --storage.path=/data"
                 alertmanager             20 minutes ago   Up 19 minutes             9093/tcp
signoz-clickhouse               clickhouse/clickhouse-server:23.7.3-alpine   "/entrypoint.sh"
                 clickhouse               20 minutes ago   Up 20 minutes (healthy)   0.0.0.0:8123->8123/tcp, :::8123->8123/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 0.0.0.0:9181->9181/tcp, :::9181->9181/tcp, 9009/tcp
signoz-frontend                 signoz/frontend:0.30.0                       "nginx -g 'daemon off;'"
                 frontend                 20 minutes ago   Up 19 minutes             80/tcp, 0.0.0.0:3301->3301/tcp, :::3301->3301/tcp
signoz-logspout                 gliderlabs/logspout:v3.2.14                  "/bin/logspout syslog+tcp://otel-collector:2255"
                 logspout                 20 minutes ago   Up 19 minutes             80/tcp
signoz-otel-collector           signoz/signoz-otel-collector:0.79.7          "/signoz-collector --config=/etc/otel-collector-config.yaml --feature-gates=-pkg.translator.prometheus.NormalizeName"           otel-collector           20 minutes ago   Up 19 minutes             0.0.0.0:4317-4318->4317-4318/tcp, :::4317-4318->4317-4318/tcp
signoz-otel-collector-metrics   signoz/signoz-otel-collector:0.79.7          "/signoz-collector --config=/etc/otel-collector-metrics-config.yaml --feature-gates=-pkg.translator.prometheus.NormalizeName"   otel-collector-metrics   20 minutes ago   Up 19 minutes             4317-4318/tcp
signoz-query-service            signoz/query-service:0.30.0                  "./query-service -config=/root/config/prometheus.yml --prefer-delta=true"
                 query-service            20 minutes ago   Up 19 minutes (healthy)   8080/tcp
signoz-zookeeper-1              bitnami/zookeeper:3.7.1                      "/opt/bitnami/scripts/zookeeper/entrypoint.sh /opt/bitnami/scripts/zookeeper/run.sh"
                 zookeeper-1              20 minutes ago   Up 20 minutes             0.0.0.0:2181->2181/tcp, :::2181->2181/tcp, 0.0.0.0:2888->2888/tcp, :::2888->2888/tcp, 0.0.0.0:3888->3888/tcp, :::3888->3888/tcp, 8080/tcp
```

## Version information 
* **Signoz version**:  v0.30.0
* **Browser version**: Chrome 117.5938
* **Your OS and version**: Ubuntu 22.04
* **Your CPU Architecture**(ARM/Intel):  Intel

## Additional context

Any idea why no are traces showing when using HTTP with port 4318? From reading the docs, both GRPC & HTTP protocols are enabled by default in otel-collector.
