### ISSUE TITLE
[authn] api fetch appears to fail for Basic Auth

### ISSUE THREAD

**Issue by lerlacher-fm** [SigNoz/signoz#4152]
## Bug description

I have created a Basic Auth "gate" in my Signoz ingress like so:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signoz-ingress
  namespace: signoz
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.org/basic-auth-secret: basic-auth
    nginx.org/basic-auth-realm: 'Authentication Required'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - signoz.XXXXX
    secretName: tls-signoz-XXXXX
  rules:
  - host: 'signoz.XXXXX'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: signoz-release-frontend
            port:
              number: 3301
```

The motivation for doing this is that we are evaluating signoz while at the same time experimenting with our kubernetes cluster and because on its first start-up, signoz presents an unsecured "please set a new admin password" screen, we want another layer of authentication to ward off any bots or other potential attackers.

The initial page load is fine and goes through the basic auth. Most of the sub resources load, but a lot of them don't, because the browser is stripping the credentials - see the highlighted empty Authorization header:

![image](https://github.com/SigNoz/signoz/assets/148015890/f2aa8eda-ff43-4e49-a130-7a2c4f510426)

I haven't reviewed the frontend code but I have a suspicion that this is due to `{ credentials:"include" }` not being set in fetch requests (see: https://fetch.spec.whatwg.org/#cors-protocol-and-credentials)

## Expected behavior

When navigating in the browser to `signoz.XXXXX` through the ingress, a basic auth dialog should pop up and the auth credentials should be provided by the browser to every request to any resource under `signoz.XXXX`

## How to reproduce

1. Configure the signoz ingress for basic auth according to your ingress controller's spec, e.g. for nginx.org: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#auth-and-ssltls
2. Access your signoz ingress

## Version information 
* **Signoz version**: v0.34.4
* **Browser version**: Firefox 120.0.1, Chromium 119.0.6045.199
* **Your OS and version**: Kubernetes
* **Your CPU Architecture**(ARM/Intel): Intel
