### ISSUE TITLE
Address jaeger receiver deprecation warning

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#4282]
2023-12-22T11:30:55.630Z\twarn\tjaegerreceiver@v0.88.0/factory.go:49\tjaeger receiver will deprecate Thrift-gen and replace it with Proto-gen to be compatbible to jaeger 1.42.0 and higher. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18485 for more details.\t{\"kind\": \"receiver\", \"name\": \"jaeger\", \"data_type\": \"traces\"}

**Comment by LHozzan** [comment]
We are not using Jaeger and Zipkin, so, I disabled them. Looks like (working with "daemonset" and "deployment"):
```yaml
ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: true

config:
  exporters:
    logging:
      loglevel: info
    otlp:
      endpoint: opentelemetry-gateway:4317
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        exporters:
          - otlp
        receivers:
          - otlp
    telemetry:
      logs:
        level: "warn"
  receivers:
    jaeger: null
    zipkin: null
```
The change get rid of the warning message.
Hope, that helps you.
