### ISSUE TITLE
Prometheus scrape configs from Istio to Signoz

### ISSUE THREAD

**Issue by jagan012** [SigNoz/signoz#4515]
## Bug description
 I am sending prometheus scrape configs from istio namesapce to signoz-otel-collector-metrics , in prometheus logs it is saying logs are pushed to service , how do i verify that in signoz .
Also is there a way to monitor istio metrics in signoz and dashboards for istio

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

![image](https://github.com/SigNoz/signoz/assets/86112184/76102d4b-41f8-4a75-8962-efd8982a6b98)

## Expected behavior

We are expecting like this in UI
![image](https://github.com/SigNoz/signoz/assets/86112184/ebb20a97-3b89-41e2-9108-70599dd6f4ee)

## How to reproduce

NAME: signoz
LAST DEPLOYED: Thu Feb  8 14:55:43 2024
NAMESPACE: monitoring
STATUS: deployed
REVISION: 1
NOTES:
1. You have just deployed SigNoz cluster:

- EKS-Version: 1.26
- frontend version: '0.38.2'
- query-service version: '0.38.2'
- alertmanager version: '0.23.4'
- otel-collector version: '0.88.11'
- otel-collector-metrics version: '0.88.11'

## Version information 
* **Signoz version**: 0.38.1
* **Browser version**: 
* **Your OS and version**: 
* **Your CPU Architecture**(ARM/Intel): 

## Additional context
We added in otel-collector-metrics configmap 
```
prometheus:
        config:
          scrape_configs:
          - job_name: prometheus-signoz
            static_configs:
            - targets: ['prometheus.istio-system.svc.cluster.local:9090']
          - job_name: kubernetes-apiservers
            kubernetes_sd_configs:
            - namespaces:
                names:
                - istio-system
              role: endpoints
            relabel_configs:
            - action: keep
              regex: default;kubernetes;https
              source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_service_name
              - __meta_kubernetes_endpoint_port_name
            scheme: https
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
          - job_name: kubernetes-service-endpoints
            kubernetes_sd_configs:
            - namespaces:
                names:
                - istio-system
              role: endpoints
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scrape
            - action: replace
              regex: (https?)
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scheme
              target_label: __scheme__
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
              - __address__
              - __meta_kubernetes_service_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - action: replace
              source_labels:
              - __meta_kubernetes_service_name
              target_label: kubernetes_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: kubernetes_node
```
              
   While adding this scrape config in otel-collector-metrics configmap , in the otel-collector-metrics pod we are seeing jobs are added and the last log is

```
{"level":"info","timestamp":"2024-02-08T12:18:42.314Z","caller":"service/service.go:73","msg":"Client started successfully"}
{"level":"info","timestamp":"2024-02-08T12:18:42.315Z","caller":"opamp/client.go:49","msg":"Ensuring collector is running","component":"simple-client"}

```

We are expecting to see istio metrics like in prometheus in signoz frontend ui
How do we verify that the jobs are successfully scraping and where do we see that metrics.
