### ISSUE TITLE
[authn] allow deploying with a pre-set admin account

### ISSUE THREAD

**Issue by dhilgarth** [SigNoz/signoz#4593]
## Is your feature request related to a problem?

I want to setup the system with all admin accounts in place. I can do this for Traefik and Portainer, but I couldn't find any documentation to do it for Signoz

## Describe the solution you'd like
Allow setting environment variables or CLI parameters with the details of the initial admin user

## Describe alternatives you've considered
Other than manually creating a user in the UI or calling the REST endpoint, I don't see any.

#### *Thank you* for your feature request – we love each and every one!

**Comment by therealpandey** [comment]
@dhilgarth
This is on our roadmap. We will update the issue once it is live!

**Comment by therealpandey** [comment]
Hi there,
This is now supported starting with signoz version [v0.112.0](https://github.com/SigNoz/signoz/releases/tag/v0.112.0).

The snippet of configuration looks like this:
```
user:
  root:
    # Whether to enable the root user. When enabled, a root user is provisioned
    # on startup using the email and password below. The root user cannot be
    # deleted, updated, or have their password changed through the UI.
    enabled: false
    # The email address of the root user.
    email: ""
    # The password of the root user. Must meet password requirements.
    password: ""
    # The name of the organization to create or look up for the root user.
    org:
      name: default
```

> The corresponding env variables are `SIGNOZ_USER_ROOT_ENABLED`, `SIGNOZ_USER_ROOT_EMAIL`, `SIGNOZ_USER_ROOT_PASSWORD`, `SIGNOZ_USER_ROOT_ORG_NAME`.

### For fresh installs
Enable the root user to have an admin account created when deployed SigNoz. 

### For existing installs
If you want to enable it for an already existing SigNoz install, first update the name of the organization by running this in your sqlite/postgres DB

```
UPDATE organizations SET name = '<name>'
```

Then enable root user keeping the following in mind:
The name should match the value of `SIGNOZ_USER_ROOT_ORG_NAME: <name>`. Insert a suitable `<name>` at both places (the query and the env variable) (my recommendation is to name it "default").
