### ISSUE TITLE
Drop some default trace attributes for better storage

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#4981]
```
process.runtime.description
telemetry.distro.name
process.executable.path
process.runtime.name
process.command_args
```

Use example processor like the below:
```processors:
  attributes/drop_fields:
    actions:
      - key: process.runtime.description
        action: delete
      - key: telemetry.distro.name
        action: delete
      - key: process.executable.path
        action: delete
      - key: process.runtime.name
        action: delete
      - key: process.command_args
        action: delete
```

Add the above processor to the pipelines

```
service:
  pipelines:
    traces:
      receivers: [...]
      processors: [..., attributes/drop_fields, ...]
      exporters: [...]
```
