### ISSUE TITLE
Standardize ENV for query service

### ISSUE THREAD

**Issue by shivanshuraj1333** [SigNoz/signoz#5266]
Right now, there's no standard way to configure environment variables for query service, for helm installation, the below ENVs are populated but similarly to running locally the ENVs are not well defined, it should match with the docker counter part.

from a container
```yaml
         env:
         - name: CLICKHOUSE_HOST
           value: my-release-clickhouse
         - name: CLICKHOUSE_PORT
           value: "9000"
         - name: CLICKHOUSE_HTTP_PORT
           value: "8123"
         - name: CLICKHOUSE_CLUSTER
           value: cluster
         - name: CLICKHOUSE_USER
           value: admin
         - name: CLICKHOUSE_PASSWORD
           value: 27ff0399-0d3a-4bd8-919d-17c2181e6fb9
         - name: CLICKHOUSE_SECURE
           value: "false"
         - name: STORAGE
           value: clickhouse
         - name: ClickHouseUrl
           value: tcp://my-release-clickhouse:9000/?username=admin&password=27ff0399-0d3a-4bd8-919d-17c2181e6fb9
         - name: ALERTMANAGER_API_PREFIX
           value: http://my-release-signoz-alertmanager:9093/api/
```

but the same is missing for locally running the query service and the parameters are hardcoded in strings 
eg
https://github.com/SigNoz/signoz/blob/develop/pkg/query-service/app/server.go#L113
https://github.com/SigNoz/signoz/blob/develop/pkg/query-service/app/clickhouseReader/reader.go#L146
