### ISSUE TITLE
Add linters to project

### ISSUE THREAD

**Issue by shivanshuraj1333** [SigNoz/signoz#5493]
Enable linting for query-service package, use`golangci-lint`, refer [OTeL collector ](https://github.com/open-telemetry/opentelemetry-collector-contrib)for reference, on how to enable it.

**Comment by Vivekcoder43** [comment]
# Project Linting Setup

This project uses `golangci-lint` to enforce coding standards and catch potential issues early. Follow the instructions below to set up and run the linter.

## Installation

### Install golangci-lint

First, you need to install `golangci-lint`. You can do this by running:

```sh
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
```
### Configuration

**Create a .golangci.yml file in the root of your project with the following content:**
```
linters:
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

run:
  timeout: 5m
```
### Running the Linter

**Add the following command to your Makefile to run golangci-lint:**

```
lint:
    golangci-lint run
```

**You can now run the linter using:**

`make lint`

### Continuous Integration

**GitHub Actions Workflow**

_To ensure linting is performed on every push and pull request, create a GitHub Actions workflow file at .github/workflows/lint.yml:_

name: Lint

```
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1

      - name: Run golangci-lint
        run: golangci-lint run
```


Reach out to me for any additional information or queries
