### ISSUE TITLE
[authn] support automatic creation of admin account during deployment

### ISSUE THREAD

**Issue by Jasonnor** [SigNoz/signoz#6001]
## Is your feature request related to a problem?

Yes. Currently, only the first person to access the front-end can create an admin account through the UI. This approach can be problematic in automated deployment scenarios or when multiple team members need immediate admin access.

## Describe the solution you'd like

- Allow setting admin credentials via environment variables (e.g., `SIGNOZ_ADMIN_EMAIL`, `SIGNOZ_ADMIN_NAME`, `SIGNOZ_ADMIN_PASSWORD`)
- Provide command-line arguments or a configuration file option for specifying admin account details during deployment

## Describe alternatives you've considered

Using a default admin account with a randomly generated password that's output to logs (requiring immediate password change on first login).

## Additional context

This feature would be particularly useful in the following scenarios:
- Automated deployments in CI/CD pipelines
- Container orchestration environments like Kubernetes
- Multi-user teams where multiple admins need to be set up immediately
- Testing and development environments where quick setup is crucial

**Comment by ToshY** [comment]
> Thanks for opening this issue. A team member should give feedback soon. In the meantime, feel free to check out the [contributing guidelines](https://github.com/signoz/signoz/blob/main/CONTRIBUTING.md).

This has been open for almost a year without feedback from a team member. Will this be added to the roadmap or not?

**Comment by fatihaziz** [comment]
no feedback yet?

**Comment by jgaines911** [comment]
Also waiting for this one.
We have also found that traces that have been set up via automation are not being collected until this initial user is created as well.

**Comment by vikrantgupta25** [comment]
Hey everyone! This is on our roadmap and we’re planning to work on it shortly. Will update this issue with more details soon.

**Comment by therealpandey** [comment]
Hi there,
This is now supported starting with signoz version [v0.112.0](https://github.com/SigNoz/signoz/releases/tag/v0.112.0).

The snippet of configuration looks like this:
```
user:
  root:
    # Whether to enable the root user. When enabled, a root user is provisioned
    # on startup using the email and password below. The root user cannot be
    # deleted, updated, or have their password changed through the UI.
    enabled: false
    # The email address of the root user.
    email: ""
    # The password of the root user. Must meet password requirements.
    password: ""
    # The name of the organization to create or look up for the root user.
    org:
      name: default
```

> The corresponding env variables are `SIGNOZ_USER_ROOT_ENABLED`, `SIGNOZ_USER_ROOT_EMAIL`, `SIGNOZ_USER_ROOT_PASSWORD`, `SIGNOZ_USER_ROOT_ORG_NAME`.

### For fresh installs
Enable the root user to have an admin account created when deployed SigNoz. 

### For existing installs
If you want to enable it for an already existing SigNoz install, first update the name of the organization by running this in your sqlite/postgres DB

```
UPDATE organizations SET name = '<name>'
```

Then enable root user keeping the following in mind:
The name should match the value of `SIGNOZ_USER_ROOT_ORG_NAME: <name>`. Insert a suitable `<name>` at both places (the query and the env variable) (my recommendation is to name it "default").
