### ISSUE TITLE
Upgrading to 0.57.0 broke log based value widgets on existing dashboards

### ISSUE THREAD

**Issue by KieranP** [SigNoz/signoz#6304]
Have just upgraded to from 0.56.0 to 0.57.0 and my dashboards that query logs and display counts of certain events are now no longer functioning, they always report 0.

When I recreate the value widgets using the exact same query, then they show a number fine.

So seems like log widgets created in 0.56.0 or before are no longer compatible with 0.57.0 :-(

Means I need to recreate 100s of value widgets :-(

**Comment by KieranP** [comment]
I thought it might have been a query builder version issue. If I edit an existing widget, and hit "Stage & Run Query", it still doesn't work, it returns 0, but if I remove all where conditions, then run "Stage & Run Query" it gives me a correct total count, and then if I add the where conditions back on, it works as expected. So something is only updating/upgrading when the where conditions are blank. Any existing widget with where conditions is broken.

**Comment by srikanthccv** [comment]
@KieranP please share more details. When you run this query, share the logs of the query-service so we can see what are then end queries getting prepared.

**Comment by KieranP** [comment]
@srikanthccv I'd be happy to. Can you help me out with how to monitor the logs of the query-service? Then I will get these to you ASAP.

**Comment by srikanthccv** [comment]
If you are using docker, tail the logs using `docker logs --tail 100 -f signoz-query-service`; For k8s, `kubectl logs -f <query-service-pod-name> -n <namespace> --tail 100`

**Comment by KieranP** [comment]
@srikanthccv Thanks. Here's the result:

Broken widget:

```json
{"level":"INFO","timestamp":"2024-10-29T02:52:25.326Z","caller":"utils/time.go:17","msg":"Elapsed time","func_name":"GetTimeSeriesResultV3","duration":66,"source":"dashboards","client":"browser","viewName":"","query":"SELECT sum(value) as value, now() as ts FROM (SELECT toStartOfInterval(fromUnixTimestamp64Nano(timestamp), INTERVAL 4020 SECOND) AS ts, toFloat64(count(*)) as value from signoz_logs.distributed_logs_v2 where (timestamp >= 1728960745000000000 AND timestamp <= 1730170345000000000) AND (ts_bucket_start >= 1728958945 AND ts_bucket_start <= 1730170345) AND attributes_string['service.name'] IN ['demo'] AND mapContains(attributes_string, 'service.name') AND attributes_string['deployment.environment'] IN ['production','staging','uat'] AND mapContains(attributes_string, 'deployment.environment') AND lower(body) like lower('%controller%') AND lower(body) like lower('%sessionscontroller%') AND JSON_EXISTS(body, '$.\"controller\"') AND JSON_VALUE(body, '$.\"controller\"') = 'SessionsController' AND lower(body) like lower('%action%') AND lower(body) like lower('%create%') AND JSON_EXISTS(body, '$.\"action\"') AND JSON_VALUE(body, '$.\"action\"') = 'create' AND lower(body) like lower('%http%status_code%') AND JSON_EXISTS(body, '$.\"http\".\"status_code\"') AND JSONExtract(JSON_VALUE(body, '$.\"http\".\"status_code\"'), 'Int64') = 200 group by ts order by value DESC)","servicesTab":"","path":"/dashboard/76ca1344-3e98-4eee-9d3f-6b8e0c5944a1/new","dashboardID":"76ca1344-3e98-4eee-9d3f-6b8e0c5944a1","alertID":""}
```

Fixed widget:

```json
{"level":"INFO","timestamp":"2024-10-29T02:56:07.299Z","caller":"utils/time.go:17","msg":"Elapsed time","func_name":"GetTimeSeriesResultV3","duration":2085,"path":"/dashboard/76ca1344-3e98-4eee-9d3f-6b8e0c5944a1/new","dashboardID":"76ca1344-3e98-4eee-9d3f-6b8e0c5944a1","alertID":"","source":"dashboards","client":"browser","viewName":"","servicesTab":"","query":"SELECT sum(value) as value, now() as ts FROM (SELECT toStartOfInterval(fromUnixTimestamp64Nano(timestamp), INTERVAL 4020 SECOND) AS ts, toFloat64(count(*)) as value from signoz_logs.distributed_logs_v2 where (timestamp >= 1728960964000000000 AND timestamp <= 1730170564000000000) AND (ts_bucket_start >= 1728959164 AND ts_bucket_start <= 1730170564) AND lower(body) like lower('%controller%') AND lower(body) like lower('%sessionscontroller%') AND JSON_EXISTS(body, '$.\"controller\"') AND JSON_VALUE(body, '$.\"controller\"') = 'SessionsController' AND lower(body) like lower('%action%') AND lower(body) like lower('%create%') AND JSON_EXISTS(body, '$.\"action\"') AND JSON_VALUE(body, '$.\"action\"') = 'create' AND lower(body) like lower('%http%status_code%') AND JSON_EXISTS(body, '$.\"http\".\"status_code\"') AND JSONExtract(JSON_VALUE(body, '$.\"http\".\"status_code\"'), 'Int64') = 200 AND (resource_fingerprint GLOBAL IN (SELECT fingerprint FROM signoz_logs.distributed_logs_v2_resource WHERE (seen_at_ts_bucket_start >= 1728959164) AND (seen_at_ts_bucket_start <= 1730170564) AND simpleJSONExtractString(labels, 'service.name') IN ['demo'] AND (labels like '%\"service.name\":\"demo\"%') AND simpleJSONExtractString(labels, 'deployment.environment') IN ['production','staging','uat'] AND (labels like '%\"deployment.environment\":\"production\"%' OR labels like '%\"deployment.environment\":\"staging\"%' OR labels like '%\"deployment.environment\":\"uat\"%'))) group by ts order by value DESC)"}
```

**Comment by srikanthccv** [comment]
It is trying to search for keys and values in log record attributes instead of resource attributes. Exec into ClickHouse and share the output of all of the following queries.

```sql
SELECT *
FROM signoz_logs.distributed_logs_attribute_keys
WHERE name LIKE '%service%'
```

```sql
SELECT *
FROM signoz_logs.distributed_logs_resource_keys
WHERE name LIKE '%service%'
```

```sql
SELECT *
FROM signoz_logs.distributed_tag_attributes
WHERE tagKey LIKE '%service%'
LIMIT 10
```

**Comment by KieranP** [comment]
@srikanthccv  Outputs below (our clients names have been redacted)

```
SELECT *
FROM signoz_logs.distributed_logs_attribute_keys
WHERE name LIKE '%service%'

Query id: bd833a64-12d7-4696-89af-e6ffb48d98d9

┌─name─────────┬─datatype─┐
│ service.name │ String   │
└──────────────┴──────────┘

1 row in set. Elapsed: 0.002 sec.
```

```
SELECT *
FROM signoz_logs.distributed_logs_resource_keys
WHERE name LIKE '%service%'

Query id: c1a4af9c-0682-4fcc-a62c-575b2ccc2dc2

┌─name─────────┬─datatype─┐
│ service.name │ String   │
└──────────────┴──────────┘
┌─name─────────┬─datatype─┐
│ service.name │ String   │
└──────────────┴──────────┘

2 rows in set. Elapsed: 0.003 sec.
```

```
SELECT *
FROM signoz_logs.distributed_tag_attributes
WHERE tagKey LIKE '%service%'
LIMIT 10

Query id: 09f91510-cb4a-446f-8714-61b3b5de9377

┌───────────timestamp─┬─tagKey───────┬─tagType──┬─tagDataType─┬─stringTagValue─┬─int64TagValue─┬─float64TagValue─┐
│ 2024-10-29 03:06:31 │ service.name │ resource │ string      │ REDACTED        │          ᴺᵁᴸᴸ │            ᴺᵁᴸᴸ │
│ 2024-10-29 03:06:31 │ service.name │ resource │ string      │ REDACTED    │          ᴺᵁᴸᴸ │            ᴺᵁᴸᴸ │
│ 2024-10-29 03:06:31 │ service.name │ resource │ string      │ REDACTED        │          ᴺᵁᴸᴸ │            ᴺᵁᴸᴸ │
│ 2024-10-29 03:06:31 │ service.name │ resource │ string      │ REDACTED           │          ᴺᵁᴸᴸ │            ᴺᵁᴸᴸ │
└─────────────────────┴──────────────┴──────────┴─────────────┴────────────────┴───────────────┴─────────────────┘
┌───────────timestamp─┬─tagKey───────┬─tagType──┬─tagDataType─┬─stringTagValue─┬─int64TagValue─┬─float64TagValue─┐
│ 2024-10-29 03:06:21 │ service.name │ resource │ string      │ REDACTED        │          ᴺᵁᴸᴸ │            ᴺᵁᴸᴸ │
│ 2024-10-29 03:06:21 │ service.name │ resource │ string      │ REDACTED    │          ᴺᵁᴸᴸ │            ᴺᵁᴸᴸ │
│ 2024-10-29 03:06:21 │ service.name │ resource │ string      │ demo           │          ᴺᵁᴸᴸ │            ᴺᵁᴸᴸ │
│ 2024-10-29 03:06:21 │ service.name │ resource │ string      │ REDACTED        │          ᴺᵁᴸᴸ │            ᴺᵁᴸᴸ │
│ 2024-10-29 03:06:11 │ service.name │ resource │ string      │ pentest        │          ᴺᵁᴸᴸ │            ᴺᵁᴸᴸ │
│ 2024-10-29 03:06:21 │ service.name │ resource │ string      │ REDACTED           │          ᴺᵁᴸᴸ │            ᴺᵁᴸᴸ │
└─────────────────────┴──────────────┴──────────┴─────────────┴────────────────┴───────────────┴─────────────────┘

10 rows in set. Elapsed: 0.003 sec. Processed 3.01 thousand rows, 170.00 KB (1.12 million rows/s., 63.50 MB/s.)
Peak memory usage: 204.77 KiB.
```

**Comment by srikanthccv** [comment]
```
SELECT *
FROM signoz_logs.distributed_logs_attribute_keys
WHERE name LIKE '%service%'

Query id: bd833a64-12d7-4696-89af-e6ffb48d98d9

┌─name─────────┬─datatype─┐
│ service.name │ String   │
└──────────────┴──────────┘

1 row in set. Elapsed: 0.002 sec.

```

This confirms the `service.name` is an attribute instead of a resource attribute. If it was the case in past but no longer the issue, please truncate the tables (these are metadata tables and data gets added to them quickly again). 


```
TRUNCATE TABLE signoz_logs.distributed_logs_attribute_keys ON CLUSTER cluster
```

```
TRUNCATE TABLE signoz_logs.distributed_tag_attributes ON CLUSTER cluster
```

**Comment by KieranP** [comment]
@srikanthccv When we first implemented Signoz, the data was erroneously being sent as attributes instead of resource attributes (I'm still not clear on the difference, but Signoz wasn't correctly linking metrics/logs under attributes, so I switched). That was maybe 5 or 6 weeks ago. It's been using resource attributes since.

So this switch would be what is breaking the older widgets from working? Odd then that when I remove query conditions and readd the exact same ones, basically winding back up with the exact same widget, things start working :-/  I'll try the truncate and see if that helps

**Comment by KieranP** [comment]
Tried the truncation. No effect. Existing dashboard widgets still broken, and the metadata tables repopulated with the existing data they had prior to truncation.

**Comment by srikanthccv** [comment]
```
SELECT *
FROM signoz_logs.distributed_logs_attribute_keys
WHERE name LIKE '%service%'
```

Is this still returning non-zero rows? Then you need to fix the issues with the data.

**Comment by KieranP** [comment]
@srikanthccv Yes, the attribute keys have returned. But this data has been there for a while, and these dashboard widgets were working without issue in 0.56.0. So wouldn't this be considered a 0.57.0 breakage that needs a migration? And again, it works when I rebuild the widget with the exact same query params, so there must be something else going on besides the log data?

**Comment by srikanthccv** [comment]
Copy the JSON and replace the `"type": "tag"` with `"type": "resource"` for those which are resource attributes. That should fix it for all panels. Please make sure to do this only for resource attributes.

**Comment by nityanandagohain** [comment]
Can you check the same for `deployment.environment` ? because it is also changed to a resource attribute.

**Comment by nityanandagohain** [comment]
Also to confirm, does you logs have `service.name` and `deployment.environment` in attributes ?

**Comment by KieranP** [comment]
@nityanandagohain Yes, same issue with deployment.environment. When I first setup Signoz, they were added as attributes (the signoz docs weren't clear which one to use or why), but I realized that Signoz was not correlating logs/metrics properly, so changed them to resource attributes about 5 to 6 weeks ago. Thus around 1/2 our logs use attributes for service.name/deployment.environment (prior to the change), and 1/2 our logs use resource attributes (after the change).

@srikanthccv I will try the switch to type resource within the JSON.

Just so I can understand this better, when Signoz sees service.name in both attribute keys and resource keys, does it prioritize whatever is most common at the time? That might explain why when the dashboard was created, it used attributes (because all service.name's at the time were attributes), but now when I recreate, it uses resource attributes (because the majority now are on resource attributes)?

**Comment by KieranP** [comment]
Idea: It would be great if Signoz could highlight somehow when a query condition is pulling from tag keys, attribute keys, or resource keys. It is odd when the UI shows identical queries but produces different results because the conditions themselves are pointing to different things under the good.

**Comment by KieranP** [comment]
@srikanthccv Hmm, no luck with replacing `"type": "tag"` with `"type": "resource"`. The only references left in the json to tag are `selectedTracesFields`, but they shouldn't be relevant for log based dashboard widgets? Have attached the dashboard JSON for reference.

[Login & MFA Metrics.json](https://github.com/user-attachments/files/17552354/Login.MFA.Metrics.json)

**Comment by KieranP** [comment]
Actually, looks like it is working now. I needed to unselect clients from the variables dropdown and reselect them for it to start working. But it does appear to have done the trick. Thank you.

**Comment by nityanandagohain** [comment]
@KieranP you also mean that some of your services are still sending them as attributes right ?

**Comment by KieranP** [comment]
@nityanandagohain They shouldn't be. I switched them over to resource attributes about 5 to 6 weeks ago. Nothing should still be sending as attributes. Here is my config if it helps:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
        metrics:
          system.cpu.logical.count:
            enabled: true
      disk: {}
      load:
        cpu_average: true
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.limit:
            enabled: true
      network: {}
      paging: {}
      process:
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
      processes: {}
  prometheus:
    config:
      global:
        scrape_interval: 30s
      scrape_configs:
        - job_name: otel-collector-binary
          static_configs:
            - targets: ["localhost:8888"]
  filelog:
    include:
      - /home/ubuntu/shared/log/production*.log
      - /var/log/commands.log
      - /var/log/auth.log

processors:
  resource:
    attributes:
      - key: deployment.environment
        value: production
        action: upsert
      - key: service.name
        value: demo
        action: upsert
  resourcedetection:
    detectors: [env, system, ec2]
    timeout: 2s
    system:
      hostname_sources: [os]
  batch:
    send_batch_size: 1000
    timeout: 5s

extensions:
  health_check: {}
  zpages: {}

exporters:
  otlp:
    endpoint: "10.0.1.29:4317"
    tls:
      insecure: true
  logging:
    verbosity: normal

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  extensions: [health_check, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [resource, resourcedetection, batch]
      exporters: [otlp]
    metrics/internal:
      receivers: [prometheus, hostmetrics]
      processors: [resource, resourcedetection, batch]
      exporters: [otlp]
    traces:
      receivers: [otlp]
      processors: [resource, resourcedetection, batch]
      exporters: [otlp]
    logs:
      receivers: [otlp, filelog]
      processors: [resource, resourcedetection, batch]
      exporters: [otlp]
```
