### ISSUE TITLE
Signoz locally set up issue with docker/runing by install.sh

### ISSUE THREAD

**Issue by vikashsprem** [SigNoz/signoz#6314]
I run `./install.sh` (using Mac) not able to run `otel-collector-migrator-sync` container. 

```
otel-collector-migrator-sync:
    image: signoz/signoz-schema-migrator:${OTELCOL_TAG:-0.111.5}
    container_name: otel-migrator-sync
    command:
      - "sync"
      - "--dsn=tcp://clickhouse:9000"
      - "--up="
    depends_on:
      clickhouse:
        condition: service_healthy
```

<img width="1001" alt="Screenshot 2024-10-30 at 1 02 57 AM" src="https://github.com/user-attachments/assets/90148797-77e5-4c98-9eb8-4a096d23f9cf">

* logs
```
docker-compose -f docker/clickhouse-setup/docker-compose.yaml logs otel-collector-migrator-sync
otel-migrator-sync  | {"L":"info","timestamp":"2024-10-29T17:56:03.805Z","C":"signozschemamigrator/main.go:91","M":"Running migrations in sync mode","dsn":"tcp://clickhouse:8123","replication":false,"cluster-name":"cluster"}
otel-migrator-sync  | {"L":"info","timestamp":"2024-10-29T17:56:03.815Z","C":"signozschemamigrator/main.go:104","M":"Up migrations","versions":[]}
otel-migrator-sync  | {"L":"info","timestamp":"2024-10-29T17:56:03.815Z","C":"signozschemamigrator/main.go:117","M":"Down migrations","versions":[]}
otel-migrator-sync  | {"L":"info","timestamp":"2024-10-29T17:56:03.815Z","C":"signozschemamigrator/main.go:127","M":"Parsed DSN","optsError":"json: unsupported type: func(context.Context, string) (net.Conn, error)"}
otel-migrator-sync  | {"L":"info","timestamp":"2024-10-29T17:56:03.818Z","C":"signozschemamigrator/main.go:133","M":"Opened connection"}
otel-migrator-sync  | Error: failed to bootstrap migrations: failed to create dbs
otel-migrator-sync  | failed to create dbs
otel-migrator-sync  | [handshake] unexpected packet [72] from server
otel-migrator-sync  | Usage:
otel-migrator-sync  |   signoz-schema-migrator sync [flags]
otel-migrator-sync  | 
otel-migrator-sync  | Flags:
otel-migrator-sync  |       --down string   Down migrations to run, comma separated. Must provide down migrations explicitly to run
otel-migrator-sync  |   -h, --help          help for sync
otel-migrator-sync  |       --up string     Up migrations to run, comma separated. Leave empty to run all up migrations
otel-migrator-sync  | 
otel-migrator-sync  | Global Flags:
otel-migrator-sync  |       --cluster-name string   Cluster name to use while running migrations (default "cluster")
otel-migrator-sync  |       --dev                   Development mode
otel-migrator-sync  |       --dsn string            Clickhouse DSN
otel-migrator-sync  |       --replication           Enable replication
otel-migrator-sync  |
