### ISSUE TITLE
Suggest to use another port if required port is already in use when installing SigNoz

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#636]
I tried installing SigNoz with another app which used port 3000. SigNoz installation failed as it uses port 3000 for showing the frontend.

It should suggest to use another port if required port is already in use when installing SigNoz. Another idea to reduce occurence of such issues is to use very uncommon ports by default. 3000 is a very common port.

**Comment by pranay01** [comment]
Do we really need so many ports for running SigNoz?

![Screenshot 2022-01-22 at 11 13 20 PM](https://user-images.githubusercontent.com/504541/150649636-260b4b07-c4a5-4688-bdef-660f089dfb86.png)

**Comment by Nageshbansal** [comment]
Closing this.

The SigNoz now runs on 8080 rather than 3000, and with [Foundry](https://github.com/SigNoz/foundry) you can set any port you want up front. The number of services has been significantly reduced compared to earlier days in SigNoz.

```yaml
spec:
  patches:
    - target: "deployment/compose.yaml"
      operations:
        - op: replace
          path: /services/signoz-signoz-0/ports
          value:
            - "<your-port>:8080"
```

The service name comes from `metadata.name` in your casting, so it changes if you name the installation something else.
