### ISSUE TITLE
Filter shows no Hostnames! But host.name is present.

### ISSUE THREAD

**Issue by macau23** [SigNoz/signoz#6361]
## Bug description

![image](https://github.com/user-attachments/assets/218e3e14-b800-44f5-b78f-1cdba2fa660d)

The filter under Logs shows no values for Hostnames.

## Expected behavior

host.name is present from the resources provider:

```
processors:
..
  resourcedetection:
..
      resource_attributes:
        host.name:
          enabled: true
```

```
  "resources": {
    "host.name": "hostnameishere"
  },
```

## How to reproduce

1.
2.
3.

## Version information 
* **Signoz version**: v0.57.0
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):
