### ISSUE TITLE
Handle resets/first data points better with StartTimeUnixNano when it is non-zero

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz#7069]
OpenTelemetry metrics send a timestamp `StartTimeUnixNano`, indicating when the measurement started https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L178. We should be able to use this information to handle the first data points better.

**Comment by srikanthccv** [comment]
While at it, take some time to dig deep into the metrics proto and what else does it offer we don't make use of today.

Related reading https://opentelemetry.io/docs/specs/otel/metrics/supplementary-guidelines/

**Comment by srikanthccv** [comment]
@namanv3 , one of the points mentioned that, even with `_created` in place, promql doesn't return data for the first point. Can you share the setup you used to verify that?

**Comment by namanv3** [comment]
@srikanthccv I have this simple python script:
```
import time
from prometheus_client import Counter, start_http_server

c = Counter("my_counter_total", "Test counter")

start_http_server(8000)

c.inc(5)

time.sleep(61)
```
This prometheus config:
```
global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "python_app"
    static_configs:
      - targets: ["app:8000"]
```
And this docker compose:
```
version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  app:
    build: .
    ports:
      - "8000:8000"
```
That uses this Dockerfile for the app:
```
FROM python:3.11-slim

WORKDIR /app
COPY app.py .

RUN pip install prometheus-client

CMD ["python", "app.py"]
```
