### ISSUE TITLE
Select Environment/s dropdown menu not filled

### ISSUE THREAD

**Issue by redwoodsquirrel** [SigNoz/signoz#7545]
## Bug description

The dropdown menu for selecting the environment is not filled. Extending the menu selection gives me a blank collection.

![Image](https://github.com/user-attachments/assets/5a1c3b8c-ba0c-4cda-8d99-7277a173504d)

## Expected behavior
Menu filled with the values I set for the tags `deployment.environment` and/or `deployment.environmentname`.

## How to reproduce

1. Set the attributes in the config-map
2. Check the tags in spans or logs in SigNoz. Both will be present.
3. Try to select from the dropdown menu. Will still be empty.

## Version information 
* **Signoz version**: 0.77.0
* **Browser version**: Firefox 137.0 and Google Chrome Version 134.0.6998.178 (Official Build) (64-bit)
* **Your OS and version**: Windows 11
* **Your CPU Architecture**(ARM/Intel): Intel

## Additional context
Snipped from open telemetry-configmap
```
processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  attributes:
    actions:
      - key: deployment.environment.name
        value: "rtkstream_dev"
        action: insert
      - key: deployment.environment
        value: "rtkstream_dev"
        action: upsert
```
