### ISSUE TITLE
[configure] how to configure SMTP for alerts?

### ISSUE THREAD

**Issue by ghost** [SigNoz/signoz#7580]
Self in K8s
I try to set the values related with sending mail by the guide https://signoz.io/docs/operate/configuration/#configuration-options and with the GPT, but with no success. 
How and where exactly i must set up this variables:
SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__PASSWORD
SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__USERNAME
SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__FROM
SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__SMARTHOST

Currently I have a values.yaml to helm:
alertmanager:
  enabled: true
  additionalEnvs:
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__USERNAME: "<cut>"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__PASSWORD: "<cut>"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__FROM: "<cut>"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__SMARTHOST: "<cut>"

But not work. I have error on the signoz-0 pod: establish connection to server: dial tcp [::1]:25: connect: connection refused, so looks like the test communication form email alert channel goes by the localhost server which i think not exist instead of this server which i provide in variables.

**Comment by grandwizard28** [comment]
Right, the configuration needs to be:
```
signoz:
   additionalEnvs:
      SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__USERNAME: ""
....
```

alertmanager has been deprecated. https://github.com/SigNoz/signoz/issues/7245

**Comment by Boelensman1** [comment]
I tried the suggested configuration (put it into /deploy/common/signoz/prometheus.yml), this however did not seem to resolve the issue. It is still trying to connect to tcp [::1]:25.

Testing via alert channels does work, so it seems like that one uses a different way of being configured?

Any help on how to correctly setup alerting would be greatly appreciated.

**Comment by Nageshbansal** [comment]
Hey @Boelensman1 Please follow this [doc](https://signoz.io/docs/manage/administrator-guide/configuration/alertmanager/#smtp-configuration-for-email-alerts) for setting up SMTP configuration.

Let us know if you are still facing the issue :-)

**Comment by Nageshbansal** [comment]
Hey @arthurio are you still facing the issue?

**Comment by arthurio** [comment]
@Nageshbansal Yes!

**Comment by grandwizard28** [comment]
Hey @arthurio,
Can you dump your exact configuration here?

**Comment by arthurio** [comment]
Under the signoz service (`deploy/docker/docker-compose.yml`):

```yaml
      - SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__FROM=xxxx@example.com
      - SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__SMARTHOST=smtp-relay.gmail.com:587
      - SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__HELLO=signoz.example.com
      - SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__REQUIRETLS=true
      - SIGNOZ_ALERTMANAGER_SIGNOZ_EXTERNAL__URL=https://signoz.example.com
  ```

I obviously redacted the usernames and domains. Again, this works when testing the channel, but when testing the notification I get the following:

```
signoz  | {"timestamp":"2025-05-21T08:18:59.284969387Z","level":"ERROR","code":{"function":"github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert.func1","file":"/home/runner/go/pkg/mod/github.com/prometheus/alertmanager@v0.28.0/dispatch/dispatch.go","line":360},"msg":"Notify for alerts failed","logger":"github.com/SigNoz/signoz/pkg/alertmanager/signozalertmanager","pkg":"go.signoz.io/pkg/alertmanager/alertmanagerserver","component":"dispatcher","num_alerts":1,"err":"Email example/email[0]: notify retry canceled after 15 attempts: establish connection to server: dial tcp [::1]:25: connect: connection refused"}
```

The ` [::1]:25` part of the error message is what makes me think that it is using the default config and not the one from the channel.

**Comment by grandwizard28** [comment]
Can you follow these steps?

- Ensure that these settings are present in the env.
- Go to the email channel and click on save. [Basically we want to re-save it]

**Comment by arthurio** [comment]
Ok, so I:
- Saved the email channel again
- Edited it to do a test notification, which was successful
<img width="1710" alt="Image" src="https://github.com/user-attachments/assets/7e632366-9f5a-4535-a946-d848710422f9" />
- I then went back to my alert and re-selected the email channel for the notification
- Saved the alert
- Edited it to do a test notification, which showed the following:
<img width="1708" alt="Image" src="https://github.com/user-attachments/assets/cac75e3b-5b79-4965-91fb-2b3dcf7cdec8" />

And now I got a different error than last time, so making some progress:

```
signoz  | {"timestamp":"2025-05-21T21:45:29.00939344Z","level":"ERROR","code":{"function":"github.com/prometheus/alertmanager/dispatch.(*Dispatcher).processAlert.func1","file":"/home/runner/go/pkg/mod/github.com/prometheus/alertmanager@v0.28.0/dispatch/dispatch.go","line":360},"msg":"Notify for alerts failed","logger":"github.com/SigNoz/signoz/pkg/alertmanager/signozalertmanager","pkg":"go.signoz.io/pkg/alertmanager/alertmanagerserver","component":"dispatcher","num_alerts":6,"err":"Email xxx-infra/email[0]: notify retry canceled after 17 attempts: send EHLO command: EOF"}
```

**Comment by grandwizard28** [comment]
You can try setting SMTP__HELLO if that is required by your SMTP provider.

**Comment by arthurio** [comment]
It was actually a typo on  `SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__REQUIRETLS=true `, it needs to be `SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__REQUIRE__TLS`.
Not sure why the Channel test notification still worked but this is resolved for me ✅ 
I guess it's unclear why you need to save the alert before testing the notification but thank you so much for your help @grandwizard28  🙏🏻

**Comment by abidmuin** [comment]
Hi @grandwizard28, I'm facing this issue while trying to test email alert, **'require_tls' is true (default) but "smtp.xxx.com:25" does not advertise the STARTTLS extension**. Could you please have a look at it? Thanks!

SigNoz is installed in Self Hosted K8s Cluster. Below is the Helm Chart `values.yaml` file for your reference. SMTP server is internally managed and using Port 25. I've tried with a external Python script for sending email with same SMTP configuration and it worked successfully.

- SigNoz v0.87.0
- Helm Chart v0.84.0

```yaml
smtpVars:
    # -- Enable SMTP for user invitations. Sets `SMTP_ENABLED` to true when enabled.
    enabled: true
  additionalEnvs:
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__FROM: "frontline@xxx.com"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__HELLO: "smtp.yyy.com"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__SMARTHOST: "smtp.yyy.com:25"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__REQUIRE__TLS: false
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__INSECURE__SKIP__VERIFY: true
```

**Comment by therealpandey** [comment]
The configuration needs to go directly under `signoz` and not under `signoz.smtpVars`.

Try putting the configuration as follows:
```
signoz:
  additionalEnvs:
    SIGNOZ...
```

**Comment by abidmuin** [comment]
I tried with the following config, still getting same error response. **'require_tls' is true (default) but "smtp.xxx.com:25" does not advertise the STARTTLS extension**

***Note**: I have tried in both K8s (Helm Chart) and Docker, in both cases facing the exact same issue.*
*Also the variable name changed to `SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__CONFIG_INSECURE__SKIP__VERIFY`*
*Ref: https://signoz.io/docs/manage/administrator-guide/configuration/alertmanager/*

Current Helm Chart value:

```yaml
signoz:
  additionalEnvs:
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__FROM: "frontline@xxx.com"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__HELLO: "smtp.yyy.com"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__SMARTHOST: "smtp.yyy.com:25"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__REQUIRE__TLS: false
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__CONFIG_INSECURE__SKIP__VERIFY: true
```

**Comment by LePau** [comment]
Not sure if this helps anyone, but this was my config that worked with signoz helm charts.  I noticed there are mentions that alert manager is deprecated and will be replaced by the query service.  But, I've seen no clear examples there on how to set up email through the helm charts for query service.

```yaml
signoz:
  additionalEnvs:
    signoz_alertmanager_signoz_global_smtp__from: $CLUSTER_ADMIN_EMAIL
    signoz_alertmanager_signoz_global_smtp__smarthost: $SMTP_SERVER_HOSTNAME:$SMTP_SERVER_PORT
    signoz_alertmanager_signoz_global_smtp__require__tls: true
    signoz_alertmanager_signoz_global_smtp__tls__config_insecure__skip__verify: true
    signoz_alertmanager_signoz_global_smtp__tls__config__insecure__skip__verify: true
    signoz_alertmanager_signoz_global_smtp__auth__username: $SMTP_SERVER_USERNAME
    signoz_alertmanager_signoz_global_smtp__hello: $CLUSTER_BASE_DOMAIN
    signoz_alertmanager_signoz_global_smtp__auth__identity: $SMTP_SERVER_USERNAME
    signoz_alertmanager_signoz_global_smtp__auth__password:
      valueFrom:
        secretKeyRef:
          name: signoz-env-secrets
          key: SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__PASSWORD      
```

**Comment by Rusinas** [comment]
I am using Mailu and here's what finally worked for me: 
```
signoz:
  additionalEnvs:
    SIGNOZ_EMAILING_ENABLED: "true"
    SIGNOZ_EMAILING_SMTP_ADDRESS: "mailu-front.mailu.svc.cluster.local:25"
    SIGNOZ_EMAILING_SMTP_FROM: "username"
    SIGNOZ_EMAILING_SMTP_AUTH_USERNAME: "username"
    SIGNOZ_EMAILING_SMTP_AUTH_PASSWORD: "your-password"
    SIGNOZ_EMAILING_SMTP_TLS_ENABLED: "false"
    SIGNOZ_EMAILING_SMTP_TLS_INSECURE_SKIP_VERIFY: "true"

    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__SMARTHOST: "mailu-front.mailu.svc.cluster.local:25"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__FROM: "username"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__USERNAME: "username"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__PASSWORD: "your-password"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__REQUIRE__TLS: "false"
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__TLS__CONFIG_INSECURE__SKIP__VERIFY: "true"
```

Not sure if every value is necessary here, but I am too tired at this point to figure it out :D

**Comment by ravikyada** [comment]
hi @Rusinas 
Can you please share the SigNoz version you're using... facing same issues

**Comment by machisuji** [comment]
Same issue here using docker.io/signoz/signoz:v0.95.1. In the meantime the values have to go under env. This is how it looks for us:

```
signoz:
  env:
    signoz_emailing_smtp_from:
      valueFrom:
        secretKeyRef:
          name: smtp-credentials
          key: from
    signoz_emailing_smtp_host:
      valueFrom:
        secretKeyRef:
          name: smtp-credentials
          key: host
    signoz_emailing_smtp_port:
      valueFrom:
        secretKeyRef:
          name: smtp-credentials
          key: port
    signoz_emailing_smtp_auth_username:
      valueFrom:
        secretKeyRef:
          name: smtp-credentials
          key: username
    signoz_emailing_smtp_auth_password:
      valueFrom:
        secretKeyRef:
          name: smtp-credentials
          key: password
    # separate config for alert manager
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__FROM:
      valueFrom:
        secretKeyRef:
          name: smtp-credentials
          key: from
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__SMARTHOST:
      valueFrom:
        secretKeyRef:
          name: smtp-credentials
          key: address
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__USERNAME:
      valueFrom:
        secretKeyRef:
          name: smtp-credentials
          key: username
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__PASSWORD:
      valueFrom:
        secretKeyRef:
          name: smtp-credentials
          key: password
    SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__REQUIRE__TLS: "true"
```

It's weird you would even need a separate config. User invitations work. Alerts do not.

Checking the env var sin the signoz container it looks like this:

```
~ # env | grep EMAILING_SMTP
SIGNOZ_EMAILING_SMTP_PORT=587
SIGNOZ_EMAILING_SMTP_AUTH_PASSWORD=...
SIGNOZ_EMAILING_SMTP_AUTH_USERNAME=...
SIGNOZ_EMAILING_SMTP_FROM=monitoring@...
SIGNOZ_EMAILING_SMTP_HOST=smtp....
~ # env | grep GLOBAL_SMTP
SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__REQUIRE__TLS=true
SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__SMARTHOST=smtp....:587
SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__USERNAME=...
SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__HELLO=monitoring....
SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__AUTH__PASSWORD=...
SIGNOZ_ALERTMANAGER_SIGNOZ_GLOBAL_SMTP__FROM=monitoring@...
```

The logs show the following:

```
{"timestamp":"2025-11-03T14:04:37.693318043Z","level":"WARN","code":{"function":"github.com/prometheus/alertmanager/notify.RetryStage.exec","file":"/home/runner/go/pkg/mod/github.com/prometheus/alertmanager@v0.28.1/notify/notify.go","line":866},"msg":"Notify attempt failed, will retry later","logger":"github.com/SigNoz/signoz/pkg/alertmanager/signozalertmanager","pkg":"go.signoz.io/pkg/alertmanager/alertmanagerserver","component":"dispatcher","receiver":"operations","integration":"email[0]","aggrGroup":"{}/{ruleId=~\"-1|019a4998-8b86-71a8-addc-5972432b2db7\"}:{alertname=\"test alarm for email config\"}","attempts":1,"err":"establish connection to server: dial tcp [::1]:25: connect: connection refused"}
```

edit: Just upgraded to v0.99.0 and the issue remains.
