### ISSUE TITLE
Error in config.yml for installation on virtual machine

### ISSUE THREAD

**Issue by vkotletkin** [SigNoz/signoz#7587]
## Bug description

Error filling in config.yaml

## How to reproduce

1. `https://raw.githubusercontent.com/SigNoz/benchmark/main/docker/standalone/config.yaml` 
contains:
```
exporters:
  otlp:
    endpoint: "<IP of machine hosting SigNoz>:4317"
    tls:
      insecure: true
  logging:
    # verbosity of the logging export: detailed, normal, basic
    verbosity: normal
```
but we will get an error, because instead of logging it should be debug.

`https://signoz.io/docs/tutorial/opentelemetry-binary-usage-in-virtual-machine/`

this should be the same as in the config example.yaml for signoz cloud
