### ISSUE TITLE
Too many parts in table 'signoz_metrics.time_series_v4_1week'

### ISSUE THREAD

**Issue by Bobses** [SigNoz/signoz#7983]
Helo,

I have installed the SigNoz helm chart in EKS (appVersion: v0.83.0, chart version: 0.80.0). I have a dedicated node r6i.xlarge for clickhouse and zookeeper, and another r6i.xlarge node for signoz-otel-collector and signoz.

Here is my values.yaml file:
```
global:
  storageClass: sc-gp3-encrypted-waitforfirstconsumer-retain
  clusterName: "tools"
  cloud: aws

clickhouse:
  enabled: true
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
    # limits:
    #   cpu: 2000m
    #   memory: 10Gi
  installCustomStorageClass: true
  files:
    config.d/log_level.xml: |
      <clickhouse>
        <logger>
          <level>warning</level>
          <console>true</console>
        </logger>
      </clickhouse>
    config.d/merge_tree_settings.xml: |
      <clickhouse>
        <merge_tree>
          <parts_to_delay_insert>8000</parts_to_delay_insert>
          <parts_to_throw_insert>10000</parts_to_throw_insert>
        </merge_tree>
      </clickhouse>  
  nodeSelector:
    role: clickhouse
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "clickhouse"
    effect: "NoSchedule"
  persistence:
    enabled: true
    storageClass: sc-gp3-encrypted-waitforfirstconsumer-retain
    size: 512Gi 
  coldStorage:
    enabled: true
    # -- Reserve free space on default disk (in bytes)
    # Default value is 10MiB, we use 10% from 512 GiB = 512 x 0.1 = 51.2 GiB; 51.2 × 1024 × 1024 × 1024 = 54975581388.8 bytes
    defaultKeepFreeSpaceBytes: "54975581389"
    endpoint: https://clickhouse-cold-storage.s3.eu-west-1.amazonaws.com/data/
    role:
      enabled: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::111111111:role/clickhouse-instance
  clickhouseOperator: 
    nodeSelector:
      role: clickhouse
    tolerations:
    - key: "role"
      operator: "Equal"
      value: "clickhouse"
      effect: "NoSchedule"
  zookeeper: 
    persistence:
      enabled: true
      storageClass: "sc-gp3-encrypted-waitforfirstconsumer-retain"
      size: 20Gi 
    nodeSelector:
      role: clickhouse
    tolerations:
    - key: "role"
      operator: "Equal"
      value: "clickhouse"
      effect: "NoSchedule"  
  settings:
    prometheus/endpoint: /metrics
    prometheus/port: 9363
    prometheus/metrics: true
    prometheus/events: true
    prometheus/asynchronous_metrics: true

  podAnnotations:
    signoz.io/scrape: "true"
    signoz.io/port: "9363"
    signoz.io/path: "/metrics"    

signoz:
  configVars:
    telemetryEnabled: false
  nodeSelector:
    role: signoz
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "signoz"
    effect: "NoSchedule"  
  persistence:
    enabled: true
    storageClass: sc-gp3-encrypted-waitforfirstconsumer-retain
    size: 20Gi  
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: &signozHostname signoz.mydomain.com
        paths:
          - path: /
            pathType: ImplementationSpecific
            port: 8080
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      external-dns.alpha.kubernetes.io/hostname: *signozHostname
      cert-manager.io/common-name: *signozHostname
      cert-manager.io/revision-history-limit: "2"
    tls:
      - secretName: signoz-tls
        hosts:
          - *signozHostname

otelCollector:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    # limits:
    #   cpu: 1000m
    #   memory: 2048Mi
  nodeSelector:
    role: signoz
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "signoz"
    effect: "NoSchedule" 
  
  config:
    processors:
      signozspanmetrics/delta:
        dimensions_cache_size: 100000
        max_operations_to_track_per_service: 4096
      batch:
        timeout: 1s
        send_batch_size: 512  
    exporters:
      clickhousetraces:
        timeout: 30s
      clickhouselogsexporter:
        sending_queue:
          enabled: true
          num_consumers: 4
          queue_size: 10000
        retry_on_failure:
          enabled: true
          max_elapsed_time: 2m
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            max_recv_msg_size_mib: 64
          http:
            endpoint: 0.0.0.0:4318
    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [signozspanmetrics/delta, batch]
          exporters: [clickhousetraces, metadataexporter]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhousemetricswrite, metadataexporter, signozclickhousemetrics]
        logs:
          receivers: [otlp, httplogreceiver/heroku, httplogreceiver/json]
          processors: [batch]
          exporters: [clickhouselogsexporter, metadataexporter]        
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: &signozOtelCollectorHostname signoz-otel-collector.mydomain.com
        paths:
          - path: /
            pathType: Prefix
            port: 4318
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      external-dns.alpha.kubernetes.io/hostname: *signozOtelCollectorHostname
      cert-manager.io/common-name: *signozOtelCollectorHostname
      cert-manager.io/revision-history-limit: "2"
      nginx.ingress.kubernetes.io/proxy-body-size: "10m"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
      nginx.ingress.kubernetes.io/client-body-buffer-size: "10m"
      nginx.ingress.kubernetes.io/enable-cors: "true"
    tls:
      - secretName: signoz-otel-tls
        hosts:
          - *signozOtelCollectorHostname

schemaMigrator:
  enabled: true
  nodeSelector:
    role: signoz
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "signoz"
    effect: "NoSchedule"
```

In addition, I have several other EKS clusters where the OpenTelemetry Collector is deployed as a daemonset, sending data to the signoz-otel-collector from the first cluster. Applications running in those clusters also send traces, logs, and metrics to the signoz-otel-collector.

Everything works fine for a few hours. After that, I noticed the following errors:

- in the signoz-otel-collector pod:

`"name":"clickhousemetricswrite","error":"code: 252, message: Too many parts (10001 with average size of 12.94 KiB) in table 'signoz_metrics.time_series_v4_1week (1ef177a4-4a8d-40d9-a260-30f04ed5ada4)'. Merges are processing significantly slower than inserts: while pushing to view signoz_metrics.time_series_v4_1week_mv_separate_attrs (02ab556f-418b-403d-a83e-3b355bdea614): while pushing to view signoz_metrics.time_series_v4_1day_mv_separate_attrs (6d90e244-ee4c-4d36-b32e-e4369448b7cb): while pushing to view signoz_metrics.time_series_v4_6hrs_mv_separate_attrs (47890153-17b3-4398-99c6-d7c81c625b16)","interval":"5.14795946s"}`

- in the clickhouse pod:

`{"date_time":"1747655494.506347","thread_name":"TCPServerConnection ([#53])","thread_id":"854","level":"Error","query_id":"0c53f2cf-41e8-46bb-ae9b-1c0a8cd6651e","logger_name":"TCPHandler","message":"Code: 252. DB::Exception: Too many parts (10001 with average size of 12.94 KiB) in table 'signoz_metrics.time_series_v4_1week (1ef177a4-4a8d-40d9-a260-30f04ed5ada4)'. Merges are processing significantly slower than inserts: while pushing to view signoz_metrics.time_series_v4_1week_mv_separate_attrs (02ab556f-418b-403d-a83e-3b355bdea614): while pushing to view signoz_metrics.time_series_v4_1day_mv_separate_attrs (6d90e244-ee4c-4d36-b32e-e4369448b7cb): while pushing to view signoz_metrics.time_series_v4_6hrs_mv_separate_attrs (47890153-17b3-4398-99c6-d7c81c625b16). (TOO_MANY_PARTS), Stack trace (when copying this message, always include the lines below):\n\n0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x000000000c800f1b in \/usr\/bin\/clickhouse\n1. DB::Exception::Exception<unsigned long&, ReadableSize, String>(int, FormatStringHelperImpl<std::type_identity<unsigned long&>::type, std::type_identity<ReadableSize>::type, std::type_identity<String>::type>, unsigned long&, ReadableSize&&, String&&) @ 0x00000000123b1e9a in \/usr\/bin\/clickhouse\n2. DB::MergeTreeData::delayInsertOrThrowIfNeeded(Poco::Event*, std::shared_ptr<DB::Context const> const&, bool) const @ 0x00000000123b1acc in \/usr\/bin\/clickhouse\n3. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x0000000012bfe69c in \/usr\/bin\/clickhouse\n4. DB::ExceptionKeepingTransform::work() @ 0x0000000012bfdc90 in \/usr\/bin\/clickhouse\n5. DB::ExecutionThreadContext::executeTask() @ 0x000000001299371a in \/usr\/bin\/clickhouse\n6. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000001298a170 in \/usr\/bin\/clickhouse\n7. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x0000000012989928 in \/usr\/bin\/clickhouse\n8. DB::PushingPipelineExecutor::start() @ 0x000000001299b960 in \/usr\/bin\/clickhouse\n9. DB::DistributedSink::writeToLocal(DB::Cluster::ShardInfo const&, DB::Block const&, unsigned long) @ 0x0000000012271b58 in \/usr\/bin\/clickhouse\n10. DB::DistributedSink::writeAsyncImpl(DB::Block const&, unsigned long) @ 0x000000001226efd4 in \/usr\/bin\/clickhouse\n11. DB::DistributedSink::consume(DB::Chunk) @ 0x000000001226b7da in \/usr\/bin\/clickhouse\n12. DB::SinkToStorage::onConsume(DB::Chunk) @ 0x0000000012ccb7c2 in \/usr\/bin\/clickhouse\n13. void std::__function::__policy_invoker<void ()>::__call_impl<std::__function::__default_alloc_func<DB::ExceptionKeepingTransform::work()::$_1, void ()>>(std::__function::__policy_storage const*) @ 0x0000000012bfe98b in \/usr\/bin\/clickhouse\n14. DB::runStep(std::function<void ()>, DB::ThreadStatus*, std::atomic<unsigned long>*) @ 0x0000000012bfe69c in \/usr\/bin\/clickhouse\n15. DB::ExceptionKeepingTransform::work() @ 0x0000000012bfdd73 in \/usr\/bin\/clickhouse\n16. DB::ExecutionThreadContext::executeTask() @ 0x000000001299371a in \/usr\/bin\/clickhouse\n17. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x000000001298a170 in \/usr\/bin\/clickhouse\n18. DB::PipelineExecutor::executeStep(std::atomic<bool>*) @ 0x0000000012989928 in \/usr\/bin\/clickhouse\n19. DB::TCPHandler::runImpl() @ 0x0000000012920b9e in \/usr\/bin\/clickhouse\n20. DB::TCPHandler::run() @ 0x0000000012933eb9 in \/usr\/bin\/clickhouse\n21. Poco::Net::TCPServerConnection::start() @ 0x00000000153a5a72 in \/usr\/bin\/clickhouse\n22. Poco::Net::TCPServerDispatcher::run() @ 0x00000000153a6871 in \/usr\/bin\/clickhouse\n23. Poco::PooledThread::run() @ 0x000000001549f047 in \/usr\/bin\/clickhouse\n24. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001549d67d in \/usr\/bin\/clickhouse\n25. ? @ 0x00007cdb8fde3609\n26. ? @ 0x00007cdb8fd08353\n","source_file":"src\/Server\/TCPHandler.cpp; void DB::TCPHandler::runImpl()","source_line":"686"}`

When the above errors appear, the nodes from the **Infra Monitoring** menu disappear. If I extend the period, I can see them with the INACTIVE status.

I don't know if this is a bug or anything else, but I need help.

Thank you!

**Comment by srikanthccv** [comment]
> I have several other EKS clusters where the OpenTelemetry Collector is deployed as a daemonset, sending data to the signoz-otel-collector from the first cluster. Applications running in those clusters also send traces, logs, and metrics to the signoz-otel-collector.


10000 is way too many parts to let allow.

How many EKS clusters are we talking about? And roughly what is the ingestion volume? The "Too many parts" indicates that the ClickHouse is not able to merge as fast as the data being ingested.

**Comment by Bobses** [comment]
For now, I have only 3 EKS clusters - but in the future will be more (10 or 15 or more).

So, what is your suggestion regarding this part of the clickhouse configuration?

```
config.d/merge_tree_settings.xml: |
      <clickhouse>
        <merge_tree>
          <parts_to_delay_insert>8000</parts_to_delay_insert>
          <parts_to_throw_insert>10000</parts_to_throw_insert>
        </merge_tree>
      </clickhouse>  
```

**Comment by srikanthccv** [comment]
I want to understand the scale of the volume before we can change in the config. The 10k is already pretty big. If you are still running into too many parts issue, then there is a resource bottleneck (could be CPU and/or disk performance). Please share the volume of data ingested rougly (you can use metrics explorer to see samples and time series count).

**Comment by Bobses** [comment]
In the future, much more data will be sent in this SigNoz installation. Right now, I want to configure it for optimal functionality.

The r6i.xlarge instance has 4 vCPU and 32 GiB of memory. Clickhouse uses a 512GiB PVC gp3 (and S3 cold storage).

![Image](https://github.com/user-attachments/assets/1afbf5a4-69a8-4be8-b339-241b92024713)

**Comment by srikanthccv** [comment]
```
      batch:
        timeout: 1s
        send_batch_size: 512
```

I just noticed this, this is too low and ends up creating too many inserts which lead to too many parts. The general recommendation for ClickHouse is 100k rows for each insert with maximum of 1 insert for second. Please let the default config be applied for batching, in fact, you should tweak it to send more data in one write and less writes to avoid creating too many parts.

**Comment by Bobses** [comment]
I removed the custom batch configuration.

What other tweaks do you recommend?

**Comment by Bobses** [comment]
Everything looks fine now. 

Please don't close this ticket, I want to observe the behaviour for at least 12-24 hours and get back to you if anything is wrong.

Thank you!

**Comment by Bobses** [comment]
I doubled the value for  send_batch_size and increased the timeout. Let's see the behavior with the new values.

**Comment by grandwizard28** [comment]
```
      batch:
        send_batch_max_size: 25000
        send_batch_size: 20000
        timeout: 1s
```

Please try with these settings.

**Comment by Bobses** [comment]
Hmm, the proposed configuration is not good: the nodes in the Infra Monitoring menu have disappeared after a few minutes. I reverted to the previous configuration - even if the error is maintained, I can check the nodes in the Infra Monitoring menu.

**Comment by pawel-lmcb** [comment]
@Bobses is this still happening on your end or did you resolve this ? We're experiencing the same issue.

**Comment by Bobses** [comment]
Hi @pawel-lmcb,

Unfortunately, the issue persists and I found no solution. I play from time to time with the batch values, but this is not the proper solution.

**Comment by srikanthccv** [comment]
@pawel-lmcb @Bobses if you are open to the idea of getting on a call to further troubleshoot this, here is my calendly https://calendly.com/srikanth-signoz/30min.

**Comment by pawel-lmcb** [comment]
Hi @srikanthccv I scheduled time. Just FYI we're running 16 vCPUs, 256GB of memory, and all flash vSAN. Everything is 10G.

What we noticed is that if we detach the following, the VM is much happier:

DETACH TABLE signoz_metrics.samples_v4_agg_5m_mv;
DETACH TABLE signoz_metrics.samples_v4_agg_30m_mv;
DEATCH table signoz_metrics.samples_v4; 

So somehow the ingestion process into Clickhouse is consuming an incredible amount of resources.

**Comment by matheushslage** [comment]
Hi @pawel-lmcb @Bobses , I was having the same problem frequently. After trying several optimizations in Clickhouse and changing the otel agent, I identified that k8s-infra was the main cause of so many writes in Clickhouse. At the moment I removed the integration and everything is fine, I believe that the default configuration of the OpenTelemetry agent should be changed in k8s-infra as needed and also for other external agents with host metrics and others. Checking these possibilities may be the solution.

**Comment by Bobses** [comment]
We don't use the k8s-infra helm chart. We use SigNoz together with the OpenTelemetry Collector installed as a DaemonSet to collect Kubernetes metrics. The issue persists.

**Comment by ronaldorcampos** [comment]
@Bobses We have been using the docker deployment of SigNoz, we were having the issue of Infra Monitoring hosts disappearing as well. I played around with having these settings in otel collector:
```
  signozclickhousemetrics:
    dsn: tcp://clickhouse:9000/signoz_metrics
    sending_queue:
      enabled: true
      queue_size: 20000 
      num_consumers: 8
```
along with the batch settings change. 
```
  batch:
    send_batch_size: 20000
    timeout: 5s
```
For us it has worked well.

Having a dashboard in SigNoz for its own otel collector metrics proved to be very helpful in adjusting its settings. Especially seeing if the collector queue is increasing or decreasing overtime, seeing metrics processed and sent.

Hopefully that helps.
