### ISSUE TITLE
Clarification on Unusually High system.network.io Metrics in SigNoz

### ISSUE THREAD

**Issue by sihandry** [SigNoz/signoz#8101]
## Bug description

Hi SigNoz team,

We are currently using SigNoz version v0.80.0 with the following otel-collector configuration for hostmetrics, especially the network scraper. We noticed that the metric system.network.io for the interface ens5 is reporting extremely high values—up to multiple terabytes—as shown in the attached dashboard screenshots.

However, when we compare this with another monitoring solution that tracks Network in/out (bytes) on the same host and time frame, the values are much smaller (in the range of a few megabytes). This discrepancy raises concerns about the accuracy or interpretation of the system.network.io metric.

Could you clarify:
- What exactly does system.network.io measure in SigNoz? Is it cumulative or rate-based?
- Why might the reported value be so large compared to other monitoring tools?
- Is this a known issue in version v0.80.0, and would upgrading to v0.85.3 help resolve it?
- Are there additional configuration best practices to ensure accurate network metrics?

Here is a snippet of our current configuration:
```
receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu: {}
      disk:
        exclude:
          devices:
            - ^ram\d+
            - ^zram\d+
            - ^loop\d+
            - ^fd\d+
            - ^hd[a-z]\d+
            - ^sd[a-z]\d+
            - ^vd[a-z]\d+
            - ^xvd[a-z]\d+
            - ^nvme\d+n\d+p\d+
          match_type: regexp
      filesystem:
        exclude_fs_types:
          fs_types:
            - autofs
            - binfmt_misc
            - bpf
            - cgroup2?
            - configfs
            - debugfs
            - devpts
            - devtmpfs
            - fusectl
            - hugetlbfs
            - iso9660
            - mqueue
            - nsfs
            - overlay
            - proc
            - procfs
            - pstore
            - rpc_pipefs
            - securityfs
            - selinuxfs
            - squashfs
            - sysfs
            - tracefs
          match_type: strict
        exclude_mount_points:
          mount_points:
            - /dev/*
            - /proc/*
            - /sys/*
            - /run/credentials/*
            - /run/k3s/containerd/*
            - /var/lib/docker/*
            - /var/lib/containers/storage/*
            - /var/lib/kubelet/*
            - /snap/*
          match_type: regexp
      load: {}
      memory: {}
      network:
        exclude:
          interfaces:
            - ^veth.*$
            - ^docker.*$
            - ^br-.*$
            - ^flannel.*$
            - ^cali.*$
            - ^cbr.*$
            - ^cni.*$
            - ^dummy.*$
            - ^tailscale.*$
            - ^lo$
          match_type: regexp
processors:
  attributes:
    actions:
      - key: "host.name"
        value: "mongo"
        action: insert
      - key: os.type
        value: linux
        action: insert
  batch:
    timeout: 5s
    send_batch_size: 10000
    send_batch_max_size: 10000

exporters:
  debug:
    verbosity: normal
  otlp:
    endpoint: endpoint:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch, attributes]
      exporters: [debug, otlp]
```

Here are the images of evidence:

image of dashboard
![image](https://i.imgur.com/XQ3MIjy.png)

image of metric collector
![image](https://i.imgur.com/czDjhXE.png)

image of another monitoirng
![image](https://i.imgur.com/hEqaWDY.png)

## Version information 
* **Signoz version**: v0.80.0 
* **Your OS and version**: Ubuntu 20.04.1 LTS
* **Your CPU Architecture**(ARM/Intel): Intel 

Thank you for your help.

**Comment by srikanthccv** [comment]
> What exactly does system.network.io measure in SigNoz? Is it cumulative or rate-based?

The underlying metric itself is cumulative (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/networkscraper/documentation.md#systemnetworkio) but the chart shows the rate value. 


> Why might the reported value be so large compared to other monitoring tools?


Likely the there monitoring tool doesn't even consider this network interface.


>Is this a known issue in version v0.80.0, and would upgrading to v0.85.3 help resolve it?


No, there is no known issue.


> Are there additional configuration best practices to ensure accurate network metrics?


As you can see from the default config, several categories of virtual and useless network interfaces are excluded to show the right data so it's already has the goo default config.


>image of metric collector


Where did you get this output?

**Comment by srikanthccv** [comment]
Something doesn't seem right. Open this host detail window, and then look at the logs of signoz service ([this](https://github.com/SigNoz/signoz/blob/main/deploy/docker/docker-compose.yaml#L111) or pod named `signoz-0`) It should log a query that gets executed for network usage (you can search for `system_network_io`). Can you share the query here?

**Comment by sihandry** [comment]
Yes sure, Here is the [log](https://drive.google.com/file/d/1rYrp3v3jAQGWfWE0hNcSo4VVXrnHryAD/view?usp=sharing) from signoz

**Comment by srikanthccv** [comment]
```sql
SELECT 
    direction,
    device,
    toStartOfInterval(
        toDateTime(intDiv(unix_milli, 1000)), 
        INTERVAL 60 SECOND
    ) as ts,
    sum(value) / 60 as value
FROM signoz_metrics.distributed_samples_v4
INNER JOIN (
    SELECT DISTINCT 
        JSONExtractString(labels, 'direction') as direction,
        JSONExtractString(labels, 'device') as device,
        fingerprint
    FROM signoz_metrics.time_series_v4
    WHERE 
        metric_name IN ['system_network_io']
        AND temporality = 'Delta'
        AND __normalized = true
        AND unix_milli >= 1748714400000
        AND unix_milli < 1748715360000
        AND JSONExtractString(labels, 'host_name') = 'mongo-release02'
) as filtered_time_series USING fingerprint
WHERE 
    metric_name IN ['system_network_io']
    AND unix_milli >= 1748714460000
    AND unix_milli < 1748715360000
GROUP BY 
    direction, 
    device, 
    ts
ORDER BY 
    direction ASC, 
    device ASC, 
    ts ASC
```



There we have it `temporality = 'Delta'`. The metrics from the `hostmetrics` receiver are `Cumulative` by default (you can see from the previous log you shared from the collector output)


```
Jun 01 00:46:57 mongo-release02.w6.id otelcol-contrib[3896634]: system.network.io{device=ens5,direction=transmit,host.name=mongo-release02,os.type=linux} 66507086239446
Jun 01 00:46:57 mongo-release02.w6.id otelcol-contrib[3896634]: system.network.io{device=ens5,direction=receive,host.name=mongo-release02,os.type=linux} 2711511481024

...

Jun 01 00:47:27 mongo-release02.w6.id otelcol-contrib[3896634]: system.network.io{device=ens5,direction=transmit,host.name=mongo-release02,os.type=linux} 66507087733053
Jun 01 00:47:27 mongo-release02.w6.id otelcol-contrib[3896634]: system.network.io{device=ens5,direction=receive,host.name=mongo-release02,os.type=linux} 2711511753515

...

Jun 01 00:47:57 mongo-release02.w6.id otelcol-contrib[3896634]: system.network.io{device=ens5,direction=transmit,host.name=mongo-release02,os.type=linux} 66507089195649
Jun 01 00:47:57 mongo-release02.w6.id otelcol-contrib[3896634]: system.network.io{device=ens5,direction=receive,host.name=mongo-release02,os.type=linux} 2711511995881

...

Jun 01 00:48:27 mongo-release02.w6.id otelcol-contrib[3896634]: system.network.io{device=ens5,direction=transmit,host.name=mongo-release02,os.type=linux} 66507090658915
Jun 01 00:48:27 mongo-release02.w6.id otelcol-contrib[3896634]: system.network.io{device=ens5,direction=receive,host.name=mongo-release02,os.type=linux} 2711512239917

```

However the query is running against the `Delta` (which is culprit because delta logic on cumulative would give such unusually high values) and if you are seeing the output means, then there are indeed delta points being ingested. It is likely you made some custom changes somewhere, please share details regarding that.

**Comment by sihandry** [comment]
Actually, I’m only using the collector config and docker-compose like this.

Collector
```
receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu: {}
      disk:
        exclude:
          devices:
            - ^ram\d+
            - ^zram\d+
            - ^loop\d+
            - ^fd\d+
            - ^hd[a-z]\d+
            - ^sd[a-z]\d+
            - ^vd[a-z]\d+
            - ^xvd[a-z]\d+
            - ^nvme\d+n\d+p\d+
          match_type: regexp
      filesystem:
        exclude_fs_types:
          fs_types:
            - autofs
            - binfmt_misc
            - bpf
            - cgroup2?
            - configfs
            - debugfs
            - devpts
            - devtmpfs
            - fusectl
            - hugetlbfs
            - iso9660
            - mqueue
            - nsfs
            - overlay
            - proc
            - procfs
            - pstore
            - rpc_pipefs
            - securityfs
            - selinuxfs
            - squashfs
            - sysfs
            - tracefs
          match_type: strict
        exclude_mount_points:
          mount_points:
            - /dev/*
            - /proc/*
            - /sys/*
            - /run/credentials/*
            - /run/k3s/containerd/*
            - /var/lib/docker/*
            - /var/lib/containers/storage/*
            - /var/lib/kubelet/*
            - /snap/*
          match_type: regexp
      load: {}
      memory: {}
      network:
        exclude:
          interfaces:
            - ^veth.*$
            - ^docker.*$
            - ^br-.*$
            - ^flannel.*$
            - ^cali.*$
            - ^cbr.*$
            - ^cni.*$
            - ^dummy.*$
            - ^tailscale.*$
            - ^lo$
          match_type: regexp
processors:
  attributes:
    actions:
      - key: "host.name"
        value: "mongo-release02"
        action: insert
      - key: os.type
        value: linux
        action: insert
  batch:
    timeout: 5s
    send_batch_size: 10000
    send_batch_max_size: 10000

exporters:
  debug:
    verbosity: normal
  otlp:
    endpoint: endpoint:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch, attributes]
      exporters: [debug, otlp]
```


docker-compose.yaml
```
root@ip-10-10-5-184:/signoz/signoz/deploy/docker# cat docker-compose.yaml
version: "3"
x-common: &common
  networks:
    - signoz-net
  restart: unless-stopped
  logging:
    options:
      max-size: 50m
      max-file: "3"
x-clickhouse-defaults: &clickhouse-defaults
  !!merge <<: *common
  # addding non LTS version due to this fix https://github.com/ClickHouse/ClickHouse/commit/32caf8716352f45c1b617274c7508c86b7d1afab
  image: clickhouse/clickhouse-server:24.1.2-alpine
  tty: true
  labels:
    signoz.io/scrape: "true"
    signoz.io/port: "9363"
    signoz.io/path: "/metrics"
  depends_on:
    init-clickhouse:
      condition: service_completed_successfully
    zookeeper-1:
      condition: service_healthy
  healthcheck:
    test:
      - CMD
      - wget
      - --spider
      - -q
      - 0.0.0.0:8123/ping
    interval: 30s
    timeout: 5s
    retries: 3
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144
x-zookeeper-defaults: &zookeeper-defaults
  !!merge <<: *common
  image: bitnami/zookeeper:3.7.1
  user: root
  labels:
    signoz.io/scrape: "true"
    signoz.io/port: "9141"
    signoz.io/path: "/metrics"
  healthcheck:
    test:
      - CMD-SHELL
      - curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null
    interval: 30s
    timeout: 5s
    retries: 3
x-db-depend: &db-depend
  !!merge <<: *common
  depends_on:
    clickhouse:
      condition: service_healthy
    schema-migrator-sync:
      condition: service_completed_successfully
services:
  init-clickhouse:
    !!merge <<: *common
    image: clickhouse/clickhouse-server:24.1.2-alpine
    container_name: signoz-init-clickhouse
    command:
      - bash
      - -c
      - |
        version="v0.0.1"
        node_os=$$(uname -s | tr '[:upper:]' '[:lower:]')
        node_arch=$$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)
        echo "Fetching histogram-binary for $${node_os}/$${node_arch}"
        cd /tmp
        wget -O histogram-quantile.tar.gz "https://github.com/SigNoz/signoz/releases/download/histogram-quantile%2F$${version}/histogram-quantile_$${node_os}_$${node_arch}.tar.gz"
        tar -xvzf histogram-quantile.tar.gz
        mv histogram-quantile /var/lib/clickhouse/user_scripts/histogramQuantile
    restart: on-failure
    volumes:
      - ../common/clickhouse/user_scripts:/var/lib/clickhouse/user_scripts/
  zookeeper-1:
    !!merge <<: *zookeeper-defaults
    container_name: signoz-zookeeper-1
    # ports:
    #   - "2181:2181"
    #   - "2888:2888"
    #   - "3888:3888"
    volumes:
      - zookeeper-1:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9141
  clickhouse:
    !!merge <<: *clickhouse-defaults
    container_name: signoz-clickhouse
    # ports:
    #   - "9000:9000"   # ClickHouse native protocol
    #   - "8123:8123"   # HTTP interface
    #   - "9181:9181"   # Prometheus metrics
    volumes:
      - ../common/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ../common/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ../common/clickhouse/custom-function.xml:/etc/clickhouse-server/custom-function.xml
      - ../common/clickhouse/user_scripts:/var/lib/clickhouse/user_scripts/
      - ../common/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - clickhouse:/var/lib/clickhouse/
      # - ../common/clickhouse/storage.xml:/etc/clickhouse-server/config.d/storage.xml
  signoz:
    !!merge <<: *db-depend
    image: signoz/signoz:${DOCKER_TAG:-v0.80.0}
    container_name: signoz
    command:
      - --config=/root/config/prometheus.yml
      - --use-logs-new-schema=true
      - --use-trace-new-schema=true
    ports:
      - "8080:8080" # signoz port
    #   - "6060:6060"     # pprof port
    volumes:
      - ../common/signoz/prometheus.yml:/root/config/prometheus.yml
      - ../common/dashboards:/root/config/dashboards
      - sqlite:/var/lib/signoz/
    environment:
      - SIGNOZ_ALERTMANAGER_PROVIDER=signoz
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_SQLSTORE_SQLITE_PATH=/var/lib/signoz/signoz.db
      - DASHBOARDS_PATH=/root/config/dashboards
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - localhost:8080/api/v1/health
      interval: 30s
      timeout: 5s
      retries: 3
  otel-collector:
    !!merge <<: *db-depend
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-v0.111.39}
    container_name: signoz-otel-collector
    command:
      - --config=/etc/otel-collector-config.yaml
      - --manager-config=/etc/manager-config.yaml
      - --copy-path=/var/tmp/collector-config.yaml
      - --feature-gates=-pkg.translator.prometheus.NormalizeName
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ../common/signoz/otel-collector-opamp-config.yaml:/etc/manager-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
    ports:
      # - "1777:1777"     # pprof extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    depends_on:
      signoz:
        condition: service_healthy
  schema-migrator-sync:
    !!merge <<: *common
    image: signoz/signoz-schema-migrator:${OTELCOL_TAG:-v0.111.39}
    container_name: schema-migrator-sync
    command:
      - sync
      - --dsn=tcp://clickhouse:9000
      - --up=
    depends_on:
      clickhouse:
        condition: service_healthy
    restart: on-failure
  schema-migrator-async:
    !!merge <<: *db-depend
    image: signoz/signoz-schema-migrator:${OTELCOL_TAG:-v0.111.39}
    container_name: schema-migrator-async
    command:
      - async
      - --dsn=tcp://clickhouse:9000
      - --up=
    restart: on-failure
networks:
  signoz-net:
    name: signoz-net
volumes:
  clickhouse:
    driver: local
    driver_opts:
      type: none
      device: /signoz/data/clickhouse
      o: bind
  sqlite:
    driver: local
    driver_opts:
      type: none
      device: /signoz/data/sqlite
      o: bind
  zookeeper-1:
    driver: local
    driver_opts:
      type: none
      device: /signoz/data/zookeeper-1
      o: bind
```

Could we override queries on Clickhouse to prevent automatic transform?
